import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function render(){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const {default:worker}=await import(workerUrl.href);return worker.fetch(new Request("http://localhost/",{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}})}

test("server renders the three-asset production shell",async()=>{const response=await render();assert.equal(response.status,200);const html=await response.text();assert.match(html,/<title>Token Lens — HYPE、UNI、BP 基本面终端<\/title>/i);assert.match(html,/三币基本面/);assert.match(html,/HYPE/);assert.match(html,/UNI/);assert.match(html,/BP/);assert.doesNotMatch(html,/ETHFI|PENDLE|AAVE|ENA|XPL/);assert.doesNotMatch(html,/codex-preview|Your site is taking shape/i)});

test("keeps HYPE UNI and BP research modules wired",async()=>{const [page,overview,hype,hypeApi,uni,uniApi,bp,bpApi]=await Promise.all(["page.tsx","tri-overview.tsx","hype-dashboard.tsx","api/hype/route.ts","uni-dashboard.tsx","api/uni/route.ts","bp-dashboard.tsx","api/bp/route.ts"].map(path=>readFile(new URL(`../app/${path}`,import.meta.url),"utf8")));assert.match(page,/TriOverview/);assert.match(page,/HypeDashboard/);assert.match(page,/UniDashboard/);assert.match(page,/BpDashboard/);assert.match(overview,/市场与业务强度/);assert.match(overview,/供应与抛压缓冲/);assert.match(overview,/回购、销毁与永久移除/);assert.match(hype,/1D 买入销毁/);assert.match(hypeApi,/userFillsByTime/);assert.match(uni,/协议费销毁飞轮/);assert.match(uniApi,/balanceData\(DEAD\)/);assert.match(uniApi,/summary\/dexs\/uniswap/);assert.match(bp,/±0\.5% 双边深度/);assert.match(bpApi,/api\/v1\/markets/)});
