"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency="usd"|"cny";
type Period="7D"|"30D"|"90D";
type BpDetail="market"|"staking"|"supply"|"authority"|null;
type BpData={
  price:number;change24h:number;high24h:number;low24h:number;marketCap:number;fdv:number;venueVolume24h:number;allMarketVolume24h:number;trades24h:number;
  circulatingSupply:number;totalSupply:number;economicMaxSupply:number;staked:number|null;stakedPercent:number|null;unstakedCirculating:number|null;cooldownDays:number;pendingUnstake:null;pendingUnstakePublic:boolean;
  chart:Array<[number,number]>;chartSource:string;marketSource:string;circulatingSource:string;liquidity:{bestBid:number|null;bestAsk:number|null;spreadBps:number|null;bidDepth1Pct:number;askDepth1Pct:number;available:boolean};
  chain:{mint:string;supply:number;decimals:number;mintAuthority:string|null;freezeAuthority:string|null;slot:number;supplyDelta:number;mintAuthorityEnabled:boolean;freezeAuthorityEnabled:boolean}|null;
  tokenomics:{tge:{amount:number;percent:number;status:string;rule:string};preIpo:{amount:number;percent:number;status:string;rule:string};postIpo:{amount:number;percent:number;status:string;rule:string}};
  stale:boolean;failedSources:string[];fxSource:string;updatedAt:string;
};

const MINT="BPxxfRCXkUVhig4HS1Lh7kZqV6SPJhzfEk4x6fVBjPCy";
const compact=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const full=(v:number,d=0)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:d}).format(v);
const money=(v:number,c:Currency,d=2)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c.toUpperCase(),minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const time=(v:string)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(v));
const short=(v:string|null)=>v?`${v.slice(0,7)}…${v.slice(-5)}`:"已撤销";

function BpChart({data,color="#e5484d",label}:{data:Array<[number,number]>;color?:string;label:string}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas||data.length<2)return;const draw=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p={top:18,right:10,bottom:18,left:10};canvas.width=Math.max(1,w*scale);canvas.height=Math.max(1,h*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);ctx.clearRect(0,0,w,h);const styles=getComputedStyle(canvas),accent=styles.getPropertyValue("--theme-accent").trim()||color,accentFade=styles.getPropertyValue("--theme-accent-fade").trim()||"rgba(229,72,77,.18)",values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;ctx.strokeStyle="rgba(42,25,25,.08)";ctx.lineWidth=1;for(let i=0;i<4;i++){const y=p.top+(h-p.top-p.bottom)/3*i;ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}const points=data.map((row,i)=>({x:p.left+i/(data.length-1)*(w-p.left-p.right),y:p.top+(max-row[1])/range*(h-p.top-p.bottom)})),gradient=ctx.createLinearGradient(0,p.top,0,h);gradient.addColorStop(0,accentFade);gradient.addColorStop(1,"rgba(255,255,255,0)");ctx.beginPath();points.forEach((point,i)=>i?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.lineTo(points.at(-1)!.x,h-p.bottom);ctx.lineTo(points[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();points.forEach((point,i)=>i?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.strokeStyle=accent;ctx.lineWidth=2.6;ctx.lineJoin="round";ctx.stroke();const last=points.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,3.5,0,Math.PI*2);ctx.fillStyle=accent;ctx.fill()};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect()},[data,color]);
  return <canvas ref={ref} className="bp-chart" aria-label={label}/>;
}

function BpMetric({label,value,meta,tone,onClick}:{label:string;value:string;meta:string;tone?:"positive"|"negative"|"warning";onClick:()=>void}){
  return <button type="button" className="metric-card bp-metric" onClick={onClick}><span className="metric-topline"><span>{label}</span><span className="arrow">↗</span></span><strong>{value}</strong><span className={`metric-meta ${tone||""}`}>{meta}</span></button>;
}

function BpDrawer({detail,data,currency,onClose}:{detail:BpDetail;data:BpData;currency:Currency;onClose:()=>void}){
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  if(!detail)return null;
  const content={
    market:{kicker:"BP MARKET",title:"市场与流动性",body:<><div className="drawer-hero"><span>Backpack BP_USDC 实时价格</span><strong>{money(data.price,currency,4)}</strong><em className={data.change24h>=0?"positive":"negative"}>{data.change24h>=0?"+":""}{data.change24h.toFixed(2)}% · 24H</em></div><div className="detail-grid"><div><span>24H 全市场成交量</span><strong>{money(data.allMarketVolume24h,currency,0)}</strong></div><div><span>Backpack 场内成交量</span><strong>{money(data.venueVolume24h,currency,0)}</strong></div><div><span>24H 最高</span><strong>{money(data.high24h,currency,4)}</strong></div><div><span>24H 最低</span><strong>{money(data.low24h,currency,4)}</strong></div><div><span>买卖价差</span><strong>{data.liquidity.spreadBps==null?"暂不可读":`${data.liquidity.spreadBps.toFixed(1)} bps`}</strong></div><div><span>±1% 盘口深度</span><strong>{money(data.liquidity.bidDepth1Pct+data.liquidity.askDepth1Pct,currency,0)}</strong></div></div><p className="drawer-note">场内行情来自 Backpack 官方公开 API；全市场成交量使用聚合市场口径，两者分开显示，避免把单一交易所成交量误标成全市场。</p></>},
    staking:{kicker:"BP PARTICIPANT PROGRAM",title:"质押与7天解押",body:<><div className="drawer-hero"><span>Backpack 平台公开总质押</span><strong>{data.staked==null?"暂不可读":`${compact(data.staked)} BP`}</strong><em>{data.stakedPercent==null?"质押率暂不可读":`${data.stakedPercent.toFixed(2)}% 流通量已质押`}</em></div><div className="detail-grid"><div><span>解押冷却期</span><strong>{data.cooldownDays} 天</strong></div><div><span>全平台解押中总量</span><strong>官方未公开</strong></div><div><span>基础股权资格</span><strong>质押满 1 年</strong></div><div><span>Bonus 阶段</span><strong>第 2—4 年按日累积</strong></div></div><div className="notice"><strong>这不是链上验证者质押</strong><p>BP 质押属于 Backpack 平台参与者计划。公开接口只有聚合质押量，没有公开退出账号、单笔截止时间或全平台解押中数量，因此本看板不伪造退出队列。</p></div><p className="drawer-note">提前解押会重置对应仓位的股权资格计时；部分解押可先拆分仓位，未解押部分保留原始计时。最终资格受地区、活跃用户条件及官方条款约束。</p></>},
    supply:{kicker:"MILESTONE TOKENOMICS",title:"供应与里程碑",body:<><div className="drawer-hero"><span>当前公开流通阶段</span><strong>{compact(data.circulatingSupply)} BP</strong><em>{(data.circulatingSupply/data.economicMaxSupply*100).toFixed(2)}% · 10 亿经济模型上限</em></div><div className="bp-milestone-list drawer-milestones">{Object.values(data.tokenomics).map((item,index)=><div key={item.status}><b>0{index+1}</b><span><strong>{item.status}</strong><small>{full(item.amount)} BP · {item.percent}%</small><p>{item.rule}</p></span></div>)}</div><p className="drawer-note">Pre-IPO 的 3.75 亿 BP 按监管、产品与市场扩展里程碑触发，没有公开固定日期。看板只监控流通量和官方状态变化，不提供虚构倒计时。</p></>},
    authority:{kicker:"SOLANA MINT",title:"链上权限状态",body:<>{data.chain?<><div className="drawer-hero"><span>Solana 当前铸造供应</span><strong>{full(data.chain.supply,3)} BP</strong><em>Slot {full(data.chain.slot)}</em></div><div className="detail-grid"><div><span>Mint Authority</span><strong className={data.chain.mintAuthorityEnabled?"warning":"positive"}>{data.chain.mintAuthorityEnabled?"仍启用":"已撤销"}</strong></div><div><span>Freeze Authority</span><strong className={data.chain.freezeAuthorityEnabled?"warning":"positive"}>{data.chain.freezeAuthorityEnabled?"仍启用":"已撤销"}</strong></div><div><span>经济模型差额</span><strong>{full(data.chain.supplyDelta,3)} BP</strong></div><div><span>代币精度</span><strong>{data.chain.decimals} 位</strong></div></div><div className="authority-address"><span>权限地址</span><code>{data.chain.mintAuthority||"—"}</code></div><p className="drawer-note">链上权限“仍启用”是可验证的技术状态，不等同于项目一定会增发或冻结账户。看板会持续监控供应和权限字段是否变化。</p></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>Solana RPC 暂时不可读</strong><p>不会使用缓存权限状态冒充实时结果，请稍后刷新。</p></div>}</>}
  }[detail];
  return <div className="drawer-layer" role="dialog" aria-modal="true" aria-label={content.title}><button className="drawer-backdrop" type="button" onClick={onClose} aria-label="关闭详情"/><aside className="detail-drawer detail-drawer-wide"><div className="drawer-head"><div><span>{content.kicker}</span><h2>{content.title}</h2></div><button type="button" onClick={onClose} aria-label="关闭">×</button></div><div className="drawer-body">{content.body}</div><div className="drawer-source"><span className={data.stale?"fallback-dot":"live-dot"}/> BP 数据更新于 {time(data.updatedAt)}</div></aside></div>;
}

export default function BpDashboard({currency,refreshNonce=0}:{currency:Currency;refreshNonce?:number}){
  const [data,setData]=useState<BpData|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<Period>("30D"),[detail,setDetail]=useState<BpDetail>(null),[stakeHistory,setStakeHistory]=useState<Array<[number,number]>>([]);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/bp?currency=${currency}&t=${Date.now()}`);if(!response.ok)throw new Error("BP 实时数据暂时不可用");const next:BpData=await response.json();setData(next);if(next.staked!=null){const key="bp-staking-history-v1",now=new Date(next.updatedAt).getTime();let rows:Array<[number,number]>=[];try{rows=JSON.parse(localStorage.getItem(key)||"[]")}catch{}const last=rows.at(-1);if(!last||now-last[0]>=3_600_000){rows=[...rows,[now,next.staked]].slice(-2_160);localStorage.setItem(key,JSON.stringify(rows))}else rows[rows.length-1]=[now,next.staked];setStakeHistory(rows)}}catch(err){setData(null);setError(err instanceof Error?err.message:"BP 实时数据暂时不可用")}finally{setLoading(false)}},[currency]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,30_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const chart=useMemo(()=>{if(!data)return[];const days=period==="7D"?7:period==="30D"?30:90,threshold=new Date(data.updatedAt).getTime()-days*86_400_000,filtered=data.chart.filter(x=>x[0]>=threshold);return filtered.length>1?filtered:data.chart.slice(-days)},[data,period]);
  if(!data)return <section className="bp-loading" aria-live="polite"><div><span className={error?"fallback-dot":"live-dot"}/><strong>{error||"正在连接 Backpack 与 Solana 实时数据"}</strong><small>{error?"不会显示旧数据或默认行情":"行情、质押、供应与链上权限同时载入"}</small>{error?<button type="button" onClick={load}>重新获取</button>:null}</div><div className="loading-metrics">{Array.from({length:6},(_,i)=><i key={i}/>)}</div><div className="loading-panels"><i/><i/><i/></div></section>;
  const priceStart=chart[0]?.[1]??data.price,priceChange=priceStart>0?(data.price/priceStart-1)*100:0,turnover=data.marketCap>0?data.allMarketVolume24h/data.marketCap*100:0,locked=data.economicMaxSupply-data.circulatingSupply,pricePositive=priceChange>=0,stakingHigh=(data.stakedPercent??0)>=60,authorityRetained=!!data.chain&&(data.chain.mintAuthorityEnabled||data.chain.freezeAuthorityEnabled),headline=authorityRetained?"高质押率，但里程碑稀释与链上权限需持续关注":priceChange>0&&stakingHigh?"价格动能与参与度同步偏强":"市场与参与度信号分化，保持观察";
  const signals=[
    {label:"市场",title:data.change24h>=0&&priceChange>=0?"短中期动能偏强":data.change24h<0&&priceChange<0?"短中期价格承压":"短中期方向分化",detail:`24H ${data.change24h>=0?"+":""}${data.change24h.toFixed(2)}% · ${period} ${priceChange>=0?"+":""}${priceChange.toFixed(2)}% · 换手 ${turnover.toFixed(2)}%`,tone:data.change24h>=0&&priceChange>=0?"tone-positive":data.change24h<0&&priceChange<0?"tone-negative":"tone-neutral"},
    {label:"质押",title:stakingHigh?"流通筹码质押率较高":"质押参与度中等",detail:data.staked==null?"官方聚合质押量暂不可读":`${compact(data.staked)} BP 已质押 · 占流通 ${(data.stakedPercent??0).toFixed(2)}% · 解押冷却 ${data.cooldownDays} 天`,tone:stakingHigh?"tone-positive":"tone-neutral"},
    {label:"供应",title:"下一批释放由里程碑触发",detail:`当前流通 ${(data.circulatingSupply/data.economicMaxSupply*100).toFixed(1)}% · 尚未流通 ${compact(locked)} BP · 无公开固定日期`,tone:"tone-warning"},
    {label:"链上权限",title:authorityRetained?"Mint / Freeze 权限仍启用":"关键权限已撤销",detail:data.chain?`链上供应 ${compact(data.chain.supply)} BP · 经济模型差额 ${full(data.chain.supplyDelta,2)} BP`:"Solana RPC 暂不可读，不沿用旧状态",tone:authorityRetained?"tone-warning":data.chain?"tone-positive":"tone-neutral"}
  ];
  return <div className="bp-dashboard"><section className="metrics-grid" aria-label="BP 关键指标"><BpMetric label="BP 当前价格" value={money(data.price,currency,4)} meta={`${data.change24h>=0?"+":""}${data.change24h.toFixed(2)}% · Backpack`} tone={data.change24h>=0?"positive":"negative"} onClick={()=>setDetail("market")}/><BpMetric label="流通市值" value={money(data.marketCap,currency,0)} meta={`FDV ${money(data.fdv,currency,0)}`} onClick={()=>setDetail("market")}/><BpMetric label="24H 全市场成交量" value={money(data.allMarketVolume24h,currency,0)} meta={`Backpack ${money(data.venueVolume24h,currency,0)}`} onClick={()=>setDetail("market")}/><BpMetric label="流通供应" value={`${compact(data.circulatingSupply)} BP`} meta={`${(data.circulatingSupply/data.economicMaxSupply*100).toFixed(2)}% 经济模型上限`} tone="positive" onClick={()=>setDetail("supply")}/><BpMetric label="平台公开质押" value={data.staked==null?"暂不可读":`${compact(data.staked)} BP`} meta={data.stakedPercent==null?"官方聚合接口异常":`${data.stakedPercent.toFixed(2)}% 流通量`} onClick={()=>setDetail("staking")}/><BpMetric label="下一供应释放" value="里程碑触发" meta="3.75亿 BP · 无固定日期" tone="warning" onClick={()=>setDetail("supply")}/></section>
    <nav className="bp-section-nav" aria-label="BP 页面导航"><a href="#bp-overview">总览</a><a href="#bp-market">市场</a><a href="#bp-staking">质押与解押</a><a href="#bp-supply">供应里程碑</a><a href="#bp-authority">链上权限</a></nav>
    <section className="signal-board bp-signal-board" id="bp-overview"><div className="signal-board-head"><div><span className="section-kicker bp-kicker">BP AUTOMATED BRIEF</span><h1>{headline}</h1></div><p>基于 Backpack 行情与质押统计、Solana 供应权限和官方里程碑规则自动生成；每 30 秒重算。</p><em><i className={data.stale?"fallback-dot":"live-dot"}/>{data.stale?"部分源异常":"实时规则引擎"} · {time(data.updatedAt)}</em></div><div className="signal-grid">{signals.map(signal=><article className={`signal-card ${signal.tone}`} key={signal.label}><span>{signal.label}</span><strong>{signal.title}</strong><p>{signal.detail}</p></article>)}</div></section>
    <section className="dashboard-grid" id="bp-market"><article className="panel bp-price-panel"><div className="panel-head"><div><span className="section-kicker bp-kicker">BP / USDC</span><h2>价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(value=><button type="button" className={period===value?"active":""} onClick={()=>setPeriod(value)} key={value}>{value}</button>)}</div></div><div className="price-summary"><strong>{money(data.price,currency,4)}</strong><span className={pricePositive?"positive":"negative"}>{pricePositive?"↑":"↓"} {Math.abs(priceChange).toFixed(2)}%</span></div>{chart.length>1?<BpChart data={chart} label="BP 价格趋势图"/>:<div className="bp-chart-empty"><span className="fallback-dot"/>Backpack K 线暂不可读</div>}<div className="chart-foot"><span>{chart[0]?new Date(chart[0][0]).toLocaleDateString("zh-CN",{month:"short",day:"numeric"}):"—"}</span><span>{data.chartSource}</span><span>现在</span></div></article>
      <article className="panel bp-liquidity-panel"><div className="panel-head"><div><span className="section-kicker bp-kicker">MARKET DEPTH</span><h2>成交与流动性</h2></div><button className="text-button" type="button" onClick={()=>setDetail("market")}>查看口径 ↗</button></div><div className="bp-market-stats"><div><span>Backpack 24H 现货量</span><strong>{money(data.venueVolume24h,currency,0)}</strong></div><div><span>24H 成交笔数</span><strong>{full(data.trades24h)}</strong></div><div><span>买卖价差</span><strong>{data.liquidity.spreadBps==null?"—":`${data.liquidity.spreadBps.toFixed(1)} bps`}</strong></div><div><span>±1% 双边深度</span><strong>{money(data.liquidity.bidDepth1Pct+data.liquidity.askDepth1Pct,currency,0)}</strong></div></div><p className="micro-note">场内与全市场成交量分开统计 · 数据源 {data.marketSource}</p></article></section>
    <section className="dashboard-grid bp-lower-grid"><article className="panel bp-staking-panel" id="bp-staking"><div className="panel-head"><div><span className="section-kicker bp-kicker">PARTICIPANT PROGRAM</span><h2>BP 质押与7天解押</h2></div><button className="text-button" type="button" onClick={()=>setDetail("staking")}>机制详情 ↗</button></div><div className="bp-stake-hero"><div><span>平台公开总质押</span><strong>{data.staked==null?"暂不可读":compact(data.staked)}</strong><small>BP</small></div><div><span>占流通量</span><strong>{data.stakedPercent==null?"—":`${data.stakedPercent.toFixed(2)}%`}</strong><small>非总供应占比</small></div><div><span>解押冷却</span><strong>{data.cooldownDays} 天</strong><small>可取消解押请求</small></div></div><div className="bp-stake-track"><i style={{width:`${Math.min(100,data.stakedPercent??0)}%`}}/></div><div className="bp-public-limit"><span className="warning-dot"/><p><strong>全平台“解押中”数量未公开。</strong>官方公开接口只给总质押量；账户仓位、解押中数量与截止时间需要登录本人 Backpack 账户，因此看板不会显示推测值。</p></div><div className="bp-history-head"><div><span>质押量历史</span><strong>{stakeHistory.length>1?`${stakeHistory.length} 个本地快照`:"从本次访问开始记录"}</strong></div><small>每小时保留一个快照 · 存在当前设备</small></div>{stakeHistory.length>1?<BpChart data={stakeHistory} color="#315fa8" label="BP 平台公开质押历史"/>:<div className="bp-chart-empty compact"><span className={loading?"live-dot":"fallback-dot"}/>积累两个快照后显示趋势，不回填虚构历史</div>}</article>
      <article className="panel bp-supply-panel" id="bp-supply"><div className="panel-head"><div><span className="section-kicker bp-kicker">MILESTONE SUPPLY</span><h2>供应里程碑</h2></div><button className="text-button" type="button" onClick={()=>setDetail("supply")}>完整说明 ↗</button></div><div className="bp-supply-hero"><strong>{(data.circulatingSupply/data.economicMaxSupply*100).toFixed(1)}%</strong><span>当前流通</span></div><div className="bp-supply-bar"><i style={{width:`${data.circulatingSupply/data.economicMaxSupply*100}%`}}/></div><div className="bp-milestone-list">{Object.values(data.tokenomics).map((item,index)=><div key={item.status}><b>0{index+1}</b><span><strong>{item.status}</strong><small>{compact(item.amount)} BP · {item.percent}%</small></span></div>)}</div><p className="micro-note">下一阶段不是固定日期解锁；以流通量变化和官方里程碑公告为准。</p></article>
      <article className="panel bp-authority-panel" id="bp-authority"><div className="panel-head"><div><span className="section-kicker bp-kicker">SOLANA MINT</span><h2>链上权限</h2></div><button className="text-button" type="button" onClick={()=>setDetail("authority")}>查看地址 ↗</button></div>{data.chain?<><div className="bp-authority-grid"><div><span>Mint Authority</span><strong className={data.chain.mintAuthorityEnabled?"warning":"positive"}>{data.chain.mintAuthorityEnabled?"仍启用":"已撤销"}</strong><small>{short(data.chain.mintAuthority)}</small></div><div><span>Freeze Authority</span><strong className={data.chain.freezeAuthorityEnabled?"warning":"positive"}>{data.chain.freezeAuthorityEnabled?"仍启用":"已撤销"}</strong><small>{short(data.chain.freezeAuthority)}</small></div></div><div className="bp-chain-supply"><span>Solana 当前供应</span><strong>{full(data.chain.supply,3)} BP</strong><small>与10亿经济模型相差 {full(data.chain.supplyDelta,3)} BP</small></div><a className="official-cta bp-cta" href={`https://solscan.io/token/${MINT}`} target="_blank" rel="noreferrer">在 Solscan 验证 ↗</a></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>Solana RPC 暂不可读</strong><p>权限状态不沿用旧值。</p></div>}</article></section>
    <section className="bp-program-strip"><div><span className="section-kicker bp-kicker">PROGRAM MECHANICS</span><h2>质押福利和股权资格，需要分开理解。</h2></div><div className="bp-program-cards"><article><span>平台福利</span><strong>交易费、USD收益与转账优惠</strong><small>按质押等级动态调整</small></article><article><span>基础资格</span><strong>至少连续质押1年</strong><small>提前解押会重置对应仓位计时</small></article><article><span>长期 Bonus</span><strong>第2—4年按日累积</strong><small>最终受 IPO、地区和官方条款约束</small></article></div></section>
    <footer className="bp-footer"><p>BP 质押是 Backpack 平台计划，不是 Solana 验证者质押；不构成投资、法律或税务建议。</p><div><a href="https://backpack.exchange/bp" target="_blank" rel="noreferrer">BP 官方页面 ↗</a><a href="https://support.backpack.exchange/exchange/programs/backpack-participant-program" target="_blank" rel="noreferrer">参与者计划 ↗</a></div></footer>
    <BpDrawer detail={detail} data={data} currency={currency} onClose={()=>setDetail(null)}/></div>;
}
