"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency="usd";
type TokenId="ethfi"|"bp"|"pendle"|"hype";
type Market={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;totalSupply:number;chart:Array<[number,number]>;stale:boolean;updatedAt:string};
type Chain={staked:number;pending:number;pendingComplete:boolean;updatedAt:string};
type Buyback={distributed30d:number;distributed90d:number;updatedAt:string};
type Bp={price:number;change24h:number;marketCap:number;fdv:number;venueVolume24h:number;allMarketVolume24h:number;circulatingSupply:number;economicMaxSupply:number;staked:number|null;stakedPercent:number|null;cooldownDays:number;chart:Array<[number,number]>;tokenomics:{preIpo:{percent:number;status:string;rule:string};postIpo:{percent:number;status:string;rule:string}};failedSources:string[];stale:boolean;updatedAt:string};
type Pendle={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;totalSupply:number;chart:Array<[number,number]>;spendle:{totalPendleStaked:number;latestBuyback:{timestamp:number;buyback:number}|null;withdrawalDays:number;instantExitFee:number}|null;terminalInflationRate:number;failedSources:string[];stale:boolean;updatedAt:string;currencyRate:number};
type PendleMarkets={totalTvl:number;tradingVolume:number;activeMarkets:number;expiryWindows:Array<{days:number;markets:number;tvl:number}>;stale?:boolean;updatedAt:string};
type Hype={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;maxSupply:number;chart:Array<[number,number]>;protocol:{perpsVolume24h:number;spotVolume24h:number;openInterest:number;perpMarkets:number}|null;staking:{totalStaked:number;stakingRatio:number;activeValidators:number;weightedApr:number;top5Share:number;withdrawalDays:number}|null;assistanceFund:{hype:number}|null;failedSources:string[];stale:boolean;updatedAt:string};
type Asset={id:TokenId;name:string;project:string;category:string;color:string;price:number|null;change24h:number|null;change30d:number|null;marketCap:number|null;fdv:number|null;volume24h:number|null;circulating:number|null;maximum:number|null;staking:number|null;stakingRatio:number|null;exit:string;businessLabel:string;businessValue:number|null;valueCapture:string;pressure:string;risk:string;confidence:number;updatedAt:string|null;chart:Array<[number,number]>};

const compact=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money=(v:number,c:Currency,d=2)=>{void c;return new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v)};
const pct=(v:number,d=1)=>`${v>=0?"+":""}${v.toFixed(d)}%`;
const safe=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)&&value>0?value:null;
const changeFromChart=(chart:Array<[number,number]>|undefined,current:number|null,days=30)=>{if(!chart?.length||current==null)return null;const rows=chart.slice(-(days+1)),start=rows[0]?.[1];return start>0?(current/start-1)*100:null};
const rank=(value:number|null,values:Array<number|null>)=>{if(value==null)return 0;const valid=values.filter((x):x is number=>x!=null).sort((a,b)=>a-b);if(valid.length<2)return 100;return 40+(valid.findIndex(x=>x>=value)/(valid.length-1))*60};

function CompareTrendChart({assets}:{assets:Asset[]}){
  const ref=useRef<HTMLCanvasElement>(null),series=useMemo(()=>assets.map(asset=>{const rows=asset.chart.slice(-31),base=rows[0]?.[1]??0;return {...asset,points:base>0?rows.map(([time,value])=>[time,value/base*100] as [number,number]):[]}}).filter(asset=>asset.points.length>1),[assets]);
  useEffect(()=>{const canvas=ref.current;if(!canvas||!series.length)return;const render=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p={top:20,right:18,bottom:24,left:36};canvas.width=Math.max(1,w*scale);canvas.height=Math.max(1,h*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);const values=series.flatMap(item=>item.points.map(point=>point[1])),min=Math.min(...values,100),max=Math.max(...values,100),pad=Math.max(3,(max-min)*.12),low=min-pad,high=max+pad,range=high-low||1,chartW=w-p.left-p.right,chartH=h-p.top-p.bottom;ctx.clearRect(0,0,w,h);ctx.font="9px sans-serif";ctx.fillStyle="#8a909c";ctx.textAlign="right";for(let i=0;i<4;i++){const value=high-i/3*range,y=p.top+i/3*chartH;ctx.strokeStyle=i===Math.round((high-100)/range*3)?"rgba(37,61,120,.24)":"rgba(31,43,68,.08)";ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke();ctx.fillText(value.toFixed(0),p.left-7,y+3)}series.forEach(item=>{ctx.beginPath();item.points.forEach((point,index)=>{const x=p.left+index/(item.points.length-1)*chartW,y=p.top+(high-point[1])/range*chartH;if(index)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.strokeStyle=item.color;ctx.lineWidth=2.4;ctx.lineJoin="round";ctx.stroke();const last=item.points.at(-1)!;ctx.beginPath();ctx.arc(w-p.right,p.top+(high-last[1])/range*chartH,3.5,0,Math.PI*2);ctx.fillStyle=item.color;ctx.fill()})};render();const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect()},[series]);
  return <canvas ref={ref} className="compare-trend-canvas" aria-label="ETHFI、BP、PENDLE 与 HYPE 近30日归一化价格走势"/>;
}

export default function CompareDashboard({currency,refreshNonce=0,ethfiMarket,ethfiChain,ethfiBuyback,onSelect}:{currency:Currency;refreshNonce?:number;ethfiMarket:Market|null;ethfiChain:Chain|null;ethfiBuyback:Buyback|null;onSelect:(token:TokenId)=>void}){
  const [bp,setBp]=useState<Bp|null>(null),[pendle,setPendle]=useState<Pendle|null>(null),[pendleMarkets,setPendleMarkets]=useState<PendleMarkets|null>(null),[hype,setHype]=useState<Hype|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState<string[]>([]);
  const [now]=useState(()=>Date.now());
  const load=useCallback(async()=>{setLoading(true);const stamp=Date.now(),requests=[fetch(`/api/bp?currency=${currency}&t=${stamp}`),fetch(`/api/pendle?currency=${currency}&t=${stamp}`),fetch(`/api/pendle-markets?t=${stamp}`),fetch(`/api/hype?currency=${currency}&t=${stamp}`)],results=await Promise.allSettled(requests.map(async responsePromise=>{const response=await responsePromise;if(!response.ok)throw new Error(String(response.status));return response.json()})),errors:string[]=[];
    if(results[0].status==="fulfilled")setBp(results[0].value as Bp);else errors.push("BP");
    if(results[1].status==="fulfilled")setPendle(results[1].value as Pendle);else errors.push("PENDLE");
    if(results[2].status==="fulfilled")setPendleMarkets(results[2].value as PendleMarkets);else errors.push("PENDLE市场");
    if(results[3].status==="fulfilled")setHype(results[3].value as Hype);else errors.push("HYPE");
    setFailed(errors);setLoading(false)},[currency]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const assets=useMemo<Asset[]>(()=>{
    const unlockDates=["2026-09-15","2026-10-15","2026-11-15","2026-12-15"],unlock90=unlockDates.filter(value=>{const at=new Date(`${value}T00:00:00+08:00`).getTime();return at>now&&at<=now+90*86_400_000}).length*8_945_833,pendleRate=pendle?.currencyRate||1;
    const ethfiQuality=[ethfiMarket?.price,ethfiMarket?.marketCap,ethfiMarket?.fdv,ethfiMarket?.volume24h,ethfiMarket?.circulatingSupply,ethfiMarket?.chart?.length,ethfiChain?.staked,ethfiBuyback?.distributed30d].filter(Boolean).length;
    const bpQuality=[bp?.price,bp?.marketCap,bp?.fdv,bp?.venueVolume24h,bp?.circulatingSupply,bp?.chart?.length,bp?.staked].filter(Boolean).length;
    const pendleQuality=[pendle?.price,pendle?.marketCap,pendle?.fdv,pendle?.volume24h,pendle?.circulatingSupply,pendle?.chart?.length,pendle?.spendle?.totalPendleStaked,pendleMarkets?.totalTvl].filter(Boolean).length;
    const hypeQuality=[hype?.price,hype?.marketCap,hype?.fdv,hype?.volume24h,hype?.circulatingSupply,hype?.chart?.length,hype?.staking?.totalStaked,hype?.protocol?.perpsVolume24h,hype?.assistanceFund?.hype].filter(Boolean).length;
    return [
      {id:"ethfi",name:"ETHFI",project:"ether.fi",category:"流动性质押 / 再质押",color:"#7657e8",price:safe(ethfiMarket?.price),change24h:ethfiMarket?.change24h??null,change30d:changeFromChart(ethfiMarket?.chart,safe(ethfiMarket?.price)),marketCap:safe(ethfiMarket?.marketCap),fdv:safe(ethfiMarket?.fdv),volume24h:safe(ethfiMarket?.volume24h),circulating:safe(ethfiMarket?.circulatingSupply),maximum:safe(ethfiMarket?.totalSupply),staking:safe(ethfiChain?.staked),stakingRatio:ethfiChain&&ethfiMarket?.totalSupply?ethfiChain.staked/ethfiMarket.totalSupply*100:null,exit:ethfiChain?.pendingComplete?`${compact(ethfiChain.pending)} ETHFI 退出中`:"退出队列部分不可读",businessLabel:"sETHFI 对应质押资产",businessValue:ethfiChain&&ethfiMarket?safe(ethfiChain.staked*ethfiMarket.price):null,valueCapture:ethfiBuyback?`30D 分配 ${compact(ethfiBuyback.distributed30d)} ETHFI`:"30D 分配暂不可读",pressure:ethfiMarket?.circulatingSupply?`90D 已知解锁约 ${(unlock90/ethfiMarket.circulatingSupply*100).toFixed(2)}% 流通量`:"解锁压力暂不可算",risk:"归属解锁与质押退出需分开观察",confidence:Math.round(ethfiQuality/8*100),updatedAt:ethfiMarket?.updatedAt??null,chart:ethfiMarket?.chart??[]},
      {id:"bp",name:"BP",project:"Backpack",category:"交易平台生态代币",color:"#e5484d",price:safe(bp?.price),change24h:bp?.change24h??null,change30d:changeFromChart(bp?.chart,safe(bp?.price)),marketCap:safe(bp?.marketCap),fdv:safe(bp?.fdv),volume24h:safe(bp?.venueVolume24h),circulating:safe(bp?.circulatingSupply),maximum:safe(bp?.economicMaxSupply),staking:safe(bp?.staked),stakingRatio:bp?.staked&&bp.economicMaxSupply?bp.staked/bp.economicMaxSupply*100:null,exit:bp?`${bp.cooldownDays} 天冷却期`:"暂不可读",businessLabel:"BP 现货市场成交",businessValue:safe(bp?.venueVolume24h),valueCapture:"质押权益；经营收入未公开",pressure:bp?`${bp.tokenomics.preIpo.percent}% 为里程碑触发，无固定日期`:"里程碑供应暂不可读",risk:"经营数据公开度低于链上协议",confidence:Math.round(bpQuality/7*100),updatedAt:bp?.updatedAt??null,chart:bp?.chart??[]},
      {id:"pendle",name:"PENDLE",project:"Pendle",category:"收益交易协议",color:"#19af9d",price:safe(pendle?.price),change24h:pendle?.change24h??null,change30d:changeFromChart(pendle?.chart,safe(pendle?.price)),marketCap:safe(pendle?.marketCap),fdv:safe(pendle?.fdv),volume24h:safe(pendle?.volume24h),circulating:safe(pendle?.circulatingSupply),maximum:safe(pendle?.totalSupply),staking:safe(pendle?.spendle?.totalPendleStaked),stakingRatio:pendle?.spendle&&pendle.totalSupply?pendle.spendle.totalPendleStaked/pendle.totalSupply*100:null,exit:pendle?.spendle?`${pendle.spendle.withdrawalDays} 天；立即退出 ${pendle.spendle.instantExitFee}%`:"暂不可读",businessLabel:"活跃收益市场 TVL",businessValue:pendleMarkets?safe(pendleMarkets.totalTvl*pendleRate):null,valueCapture:pendle?.spendle?.latestBuyback?`最近周期回购 ${money(pendle.spendle.latestBuyback.buyback,currency,0)}`:"最近回购暂不可读",pressure:pendle?`约 ${pendle.terminalInflationRate}% / 年终端激励排放`:"排放暂不可读",risk:"收益市场到期集中可能引发 TVL 滚动",confidence:Math.round(pendleQuality/8*100),updatedAt:pendle?.updatedAt??null,chart:pendle?.chart??[]},
      {id:"hype",name:"HYPE",project:"Hyperliquid",category:"交易链 / 网络原生资产",color:"#35c98c",price:safe(hype?.price),change24h:hype?.change24h??null,change30d:changeFromChart(hype?.chart,safe(hype?.price)),marketCap:safe(hype?.marketCap),fdv:safe(hype?.fdv),volume24h:safe(hype?.volume24h),circulating:safe(hype?.circulatingSupply),maximum:safe(hype?.maxSupply),staking:safe(hype?.staking?.totalStaked),stakingRatio:hype?.staking?hype.staking.stakingRatio*100:null,exit:hype?.staking?`${hype.staking.withdrawalDays} 天转回现货账户`:"暂不可读",businessLabel:"HyperCore 永续成交",businessValue:safe(hype?.protocol?.perpsVolume24h),valueCapture:hype?.assistanceFund?`援助基金 ${compact(hype.assistanceFund.hype)} HYPE`:"援助基金暂不可读",pressure:"质押奖励来自未来排放储备",risk:hype?.staking?`Top 5 验证者占 ${(hype.staking.top5Share*100).toFixed(1)}% 活跃质押`:"验证者集中度暂不可读",confidence:Math.round(hypeQuality/9*100),updatedAt:hype?.updatedAt??null,chart:hype?.chart??[]}
    ];
  },[currency,ethfiBuyback,ethfiChain,ethfiMarket,bp,pendle,pendleMarkets,hype,now]);
  const values=(key:keyof Pick<Asset,"marketCap"|"volume24h"|"change30d">)=>assets.map(asset=>asset[key]);
  const enhanced=assets.map(asset=>({...asset,liquidity:(rank(asset.marketCap,values("marketCap"))+rank(asset.volume24h,values("volume24h")))/2,momentum:rank(asset.change30d,values("change30d")),circulation:asset.circulating&&asset.maximum?asset.circulating/asset.maximum*100:0,stakingDepth:asset.stakingRatio??0}));
  const leader=(selector:(asset:typeof enhanced[number])=>number|null)=>enhanced.filter(asset=>selector(asset)!=null).sort((a,b)=>(selector(b)??-Infinity)-(selector(a)??-Infinity))[0];
  const leaders=[
    {label:"规模领先",asset:leader(x=>x.marketCap),detail:(x:Asset)=>x.marketCap?`市值 ${money(x.marketCap,currency,0)}`:"—"},
    {label:"交易活跃",asset:leader(x=>x.marketCap&&x.volume24h?x.volume24h/x.marketCap:null),detail:(x:Asset)=>x.marketCap&&x.volume24h?`换手率 ${(x.volume24h/x.marketCap*100).toFixed(1)}%`:"—"},
    {label:"30D 动能",asset:leader(x=>x.change30d),detail:(x:Asset)=>x.change30d!=null?pct(x.change30d):"—"},
    {label:"流通最充分",asset:leader(x=>x.circulating&&x.maximum?x.circulating/x.maximum:null),detail:(x:Asset)=>x.circulating&&x.maximum?`${(x.circulating/x.maximum*100).toFixed(1)}% 已流通`:"—"},
    {label:"质押最深入",asset:leader(x=>x.stakingRatio),detail:(x:Asset)=>x.stakingRatio!=null?`${x.stakingRatio.toFixed(1)}% 最大供应`:"—"}
  ].filter(item=>item.asset);
  const rows=[
    {label:"当前价格",render:(x:Asset)=>x.price?money(x.price,currency,4):"暂不可读"},{label:"24H 涨跌",render:(x:Asset)=>x.change24h!=null?pct(x.change24h,2):"暂不可读",tone:(x:Asset)=>x.change24h},
    {label:"30D 涨跌",render:(x:Asset)=>x.change30d!=null?pct(x.change30d,2):"暂不可读",tone:(x:Asset)=>x.change30d},{label:"流通市值",render:(x:Asset)=>x.marketCap?money(x.marketCap,currency,0):"暂不可读"},
    {label:"FDV",render:(x:Asset)=>x.fdv?money(x.fdv,currency,0):"暂不可读"},{label:"24H 现货量",render:(x:Asset)=>x.volume24h?money(x.volume24h,currency,0):"暂不可读"},
    {label:"成交额 / 市值",render:(x:Asset)=>x.volume24h&&x.marketCap?`${(x.volume24h/x.marketCap*100).toFixed(1)}%`:"暂不可比"},{label:"流通率",render:(x:Asset)=>x.circulating&&x.maximum?`${(x.circulating/x.maximum*100).toFixed(1)}%`:"暂不可比"},
    {label:"质押 / 最大供应",render:(x:Asset)=>x.stakingRatio!=null?`${x.stakingRatio.toFixed(1)}%`:"暂不可比"},{label:"质押退出",render:(x:Asset)=>x.exit},{label:"业务参考",render:(x:Asset)=>x.businessValue?`${x.businessLabel} · ${money(x.businessValue,currency,0)}`:`${x.businessLabel} · 暂不可读`}
  ];
  return <div className="compare-dashboard">
    <section className="compare-hero" id="compare-overview"><div><span className="section-kicker">CROSS-ASSET RESEARCH</span><h1>先看谁领先，<em>再看为什么。</em></h1><p>四币统一使用 USD 市场口径；供应、质押、业务与风险分别比较，不用一个总分掩盖差异。</p></div><aside><span className={loading?"fallback-dot":"live-dot"}/><strong>{loading?"正在刷新四币数据":"比较数据已同步"}</strong><small>{failed.length?`${failed.join("、")} 暂不可读，其余模块正常`:`${assets.filter(x=>x.confidence>=80).length}/4 个资产数据完整度达到 80%`}</small></aside></section>
    <section className="compare-leader-block"><div className="compare-leader-head"><div><span className="section-kicker">LEADING NOW</span><h2>当前优势一览</h2></div><p>同口径指标动态选出领先者</p></div><div className="compare-leaders" aria-label="当前领先指标">{leaders.map(item=>{const asset=item.asset!;return <button type="button" onClick={()=>onSelect(asset.id)} style={{"--asset":asset.color} as React.CSSProperties} key={item.label}><span>{item.label}</span><strong>{asset.name}</strong><small>{item.detail(asset)}</small><em>查看依据 →</em></button>})}</div></section>
    <section className="panel compare-chart-panel"><div className="panel-head"><div><span className="section-kicker">RELATIVE PERFORMANCE</span><h2>30D 相对价格走势</h2></div><span className="compare-note">各币起点统一为 100</span></div><div className="compare-chart-legend">{assets.map(asset=><span style={{"--asset":asset.color} as React.CSSProperties} key={asset.id}><i/><b>{asset.name}</b><em className={asset.change30d==null?"":asset.change30d>=0?"positive":"negative"}>{asset.change30d==null?"—":pct(asset.change30d)}</em></span>)}</div><CompareTrendChart assets={assets}/></section>
    <section className="panel compare-matrix-panel"><div className="panel-head"><div><span className="section-kicker">UNIFIED MATRIX</span><h2>核心指标矩阵</h2></div><span className="compare-note">金额统一为 USD · 领先只比较同口径原始值</span></div><div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>指标</th>{assets.map(asset=><th key={asset.id}><button type="button" onClick={()=>onSelect(asset.id)}><i style={{background:asset.color}}/><span><b>{asset.name}</b><small>{asset.category}</small></span></button></th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.label}><th>{row.label}</th>{assets.map(asset=>{const tone=row.tone?.(asset);return <td className={tone==null?"":tone>=0?"positive":"negative"} key={asset.id}>{row.render(asset)}</td>})}</tr>)}</tbody></table></div></section>
    <section className="compare-strength-section"><div className="compare-section-head"><div><span className="section-kicker">ADVANTAGE MAP</span><h2>优势地图</h2></div><p>市场与动能采用四币相对排名；流通、质押和完整度展示原始比例。没有统一总分。</p></div><div className="compare-strength-grid">{enhanced.map(asset=><article style={{"--asset":asset.color} as React.CSSProperties} key={asset.id}><header><div><i/><span><strong>{asset.name}</strong><small>{asset.project}</small></span></div><button type="button" onClick={()=>onSelect(asset.id)}>详情 ↗</button></header><div className="strength-bars">{[{label:"市场流动性",value:asset.liquidity,text:`相对 ${Math.round(asset.liquidity)}`},{label:"30D 动能",value:asset.momentum,text:asset.change30d!=null?pct(asset.change30d):"未知"},{label:"供应已释放",value:asset.circulation,text:`${asset.circulation.toFixed(1)}%`},{label:"质押深度",value:Math.min(100,asset.stakingDepth),text:asset.stakingRatio!=null?`${asset.stakingRatio.toFixed(1)}%`:"未知"},{label:"数据完整度",value:asset.confidence,text:`${asset.confidence}%`}].map(metric=><div key={metric.label}><span><b>{metric.label}</b><small>{metric.text}</small></span><i><b style={{width:`${Math.max(0,metric.value)}%`}}/></i></div>)}</div><div className="asset-thesis"><span>价值回流</span><strong>{asset.valueCapture}</strong><p>{asset.risk}</p></div></article>)}</div></section>
    <section className="compare-valuation-grid"><article className="panel"><div className="panel-head"><div><span className="section-kicker">RELATIVE VALUATION</span><h2>估值与业务参照</h2></div></div><div className="valuation-list">{assets.map(asset=><div key={asset.id}><span><i style={{background:asset.color}}/><b>{asset.name}</b><small>{asset.businessLabel}</small></span><div><em>FDV / 市值</em><strong>{asset.fdv&&asset.marketCap?`${(asset.fdv/asset.marketCap).toFixed(2)}×`:"—"}</strong></div><div><em>业务参照 / FDV</em><strong>{asset.businessValue&&asset.fdv?`${(asset.businessValue/asset.fdv*100).toFixed(2)}%`:"—"}</strong></div></div>)}</div><p className="micro-note">“业务参照”分别为质押资产、BP 现货成交、Pendle 活跃市场 TVL、HyperCore 永续成交；用于理解各自规模，不跨业务排名。</p></article><article className="panel"><div className="panel-head"><div><span className="section-kicker">VALUE CAPTURE</span><h2>价值回流证据</h2></div></div><div className="capture-list">{assets.map(asset=><div key={asset.id}><span><i style={{background:asset.color}}/><b>{asset.name}</b></span><strong>{asset.valueCapture}</strong><small>{asset.pressure}</small></div>)}</div></article></section>
    <section className="panel compare-radar"><div className="panel-head"><div><span className="section-kicker">90-DAY RADAR</span><h2>未来事件与持续压力</h2></div><span className="compare-note">固定日期、条件触发、持续机制分开看</span></div><div className="risk-table"><div className="risk-row head"><span>资产</span><span>类型</span><span>事件 / 压力</span><span>观察指标</span></div><div className="risk-row" style={{"--asset":"#7657e8"} as React.CSSProperties}><strong><i/>ETHFI</strong><span>固定日期</span><b>9/15 · 10/15 · 11/15</b><em>每次约 894.58 万枚</em></div><div className="risk-row" style={{"--asset":"#e5484d"} as React.CSSProperties}><strong><i/>BP</strong><span>条件触发</span><b>Pre-IPO 里程碑供应</b><em>37.5% · 无固定日期</em></div><div className="risk-row" style={{"--asset":"#19af9d"} as React.CSSProperties}><strong><i/>PENDLE</strong><span>持续机制</span><b>激励排放 + 市场到期</b><em>约 2% / 年 · 30/90D TVL</em></div><div className="risk-row" style={{"--asset":"#35c98c"} as React.CSSProperties}><strong><i/>HYPE</strong><span>持续机制</span><b>质押奖励排放</b><em>解除后 7 天转出现货</em></div></div></section>
    <footer className="compare-footer"><div><span className="brand-mark small">t</span><strong>Token Lens Compare</strong></div><p>相对领先不等于投资建议；缺失项不计零分，跨业务指标不参与排名。</p><div>{assets.map(asset=><button type="button" onClick={()=>onSelect(asset.id)} key={asset.id}>{asset.name} ↗</button>)}</div></footer>
  </div>;
}
