"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { expandedAssetMeta,type ExpandedAssetSnapshot,type ExpandedAssetsResponse,type ExpandedTokenId } from "./asset-model";

const compact=(value:number,digits=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:digits}).format(value);
const money=(value:number,digits=2)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value);
const readable=(value:number|null,suffix="")=>value==null?"暂不可读":`${compact(value)}${suffix}`;

function SnapshotChart({data,color,label}:{data:Array<[number,number]>;color:string;label:string}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas||data.length<2)return;const draw=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p={top:18,right:12,bottom:20,left:12};canvas.width=Math.max(1,w*scale);canvas.height=Math.max(1,h*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);ctx.clearRect(0,0,w,h);const values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1,start=data[0][0],end=data.at(-1)![0],timeRange=end-start||1;for(let i=0;i<4;i++){const y=p.top+i/3*(h-p.top-p.bottom);ctx.strokeStyle="rgba(31,43,68,.08)";ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}const points=data.map(row=>({x:p.left+(row[0]-start)/timeRange*(w-p.left-p.right),y:p.top+(max-row[1])/range*(h-p.top-p.bottom)}));const gradient=ctx.createLinearGradient(0,p.top,0,h-p.bottom);gradient.addColorStop(0,`${color}33`);gradient.addColorStop(1,`${color}00`);ctx.beginPath();points.forEach((point,index)=>index?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.lineTo(points.at(-1)!.x,h-p.bottom);ctx.lineTo(points[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();points.forEach((point,index)=>index?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.lineJoin="round";ctx.stroke();const last=points.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,3.5,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect()},[data,color]);
  return <canvas ref={ref} className="expanded-chart" aria-label={label}/>;
}

export default function ExpandedAssetDashboard({token,refreshNonce=0}:{token:ExpandedTokenId;refreshNonce?:number}){
  const [asset,setAsset]=useState<ExpandedAssetSnapshot|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<"30D"|"90D">("30D");
  const meta=expandedAssetMeta[token];
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/expanded-assets?t=${Date.now()}`);if(!response.ok)throw new Error("实时数据暂时不可用");const payload=await response.json() as ExpandedAssetsResponse,next=payload.assets.find(item=>item.id===token);if(!next)throw new Error("资产快照暂时不可用");setAsset(next)}catch(error){setAsset(null);setError(error instanceof Error?error.message:"实时数据暂时不可用")}finally{setLoading(false)}},[token]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const chart=useMemo(()=>asset?.chart.slice(period==="30D"?-31:-90)??[],[asset,period]);
  if(!asset)return <section className="expanded-loading" aria-live="polite"><span className={error?"fallback-dot":"live-dot"}/><div><strong>{error||`正在载入 ${meta.name} 标准快照`}</strong><small>{error?"不会显示缓存默认值":"市场、供应、质押与业务指标同步读取"}</small></div>{error?<button type="button" onClick={load}>重新获取</button>:null}</section>;
  const circulation=asset.circulatingSupply&&asset.overallSupply?asset.circulatingSupply/asset.overallSupply*100:null,stakingRatio=asset.stakingAmount!=null&&asset.overallSupply?asset.stakingAmount/asset.overallSupply*100:null,chartChange=chart.length>1?(chart.at(-1)![1]/chart[0][1]-1)*100:null,nextUnlock=asset.unlockEvents?.filter(event=>new Date(`${event.date}T23:59:59+08:00`).getTime()>Date.now()).sort((a,b)=>a.date.localeCompare(b.date))[0]??null,unlockSameDay=nextUnlock?asset.unlockEvents?.filter(event=>event.date===nextUnlock.date).reduce((sum,event)=>sum+event.amount,0)??nextUnlock.amount:null,unlockRatio=unlockSameDay&&asset.circulatingSupply?unlockSameDay/asset.circulatingSupply*100:null;
  return <div className="expanded-dashboard" style={{"--expanded":asset.color} as React.CSSProperties}>
    <section className="expanded-hero" id={`${token}-overview`}><div><span className="section-kicker">STANDARDIZED ASSET SNAPSHOT</span><h1>{asset.name}<em>{asset.project}</em></h1><p>{asset.category} · 市场、供应、质押及业务数据按统一模型展示。</p></div><aside><span className={asset.failedSources.length?"fallback-dot":"live-dot"}/><strong>{asset.failedSources.length?"部分数据源暂不可读":"实时数据源正常"}</strong><small>{asset.failedSources.length?asset.failedSources.join(" · "):new Date(asset.updatedAt).toLocaleTimeString("zh-CN")}</small></aside></section>
    <section className="metrics-grid expanded-metrics" aria-label={`${asset.name} 关键指标`}><article><span>当前价格</span><strong>{asset.price==null?"暂不可读":money(asset.price,4)}</strong><small className={(asset.change24h??0)>=0?"positive":"negative"}>{asset.change24h==null?"24H 暂不可读":`${asset.change24h>=0?"+":""}${asset.change24h.toFixed(2)}% · 24H`}</small></article><article><span>流通市值</span><strong>{asset.marketCap==null?"暂不可读":money(asset.marketCap,0)}</strong><small>{asset.fdv==null?"FDV 暂不可读":`FDV ${money(asset.fdv,0)}`}</small></article><article><span>24H 现货量</span><strong>{asset.volume24h==null?"暂不可读":money(asset.volume24h,0)}</strong><small>{asset.volume24h&&asset.marketCap?`${(asset.volume24h/asset.marketCap*100).toFixed(1)}% 成交额 / 市值`:"暂不可比"}</small></article><article><span>流通 / 整体供应</span><strong>{circulation==null?"暂不可读":`${circulation.toFixed(1)}%`}</strong><small>{readable(asset.circulatingSupply,` ${asset.name}`)}</small></article><article><span>质押 / 整体供应</span><strong>{token==="xpl"?"尚未上线":!asset.stakingApplicable?"不适用":stakingRatio==null?"暂不可读":`${stakingRatio.toFixed(1)}%`}</strong><small>{asset.stakingLabel}</small></article><article><span>{asset.businessLabel}</span><strong>{asset.businessValue==null?"暂不可读":money(asset.businessValue,0)}</strong><small>USD · 业务参照不跨项目排名</small></article></section>
    <section className="expanded-pressure-strip" aria-label={`${asset.name} 供应与价值回流`}><article className={nextUnlock?"danger":"neutral"}><span>下一供应事件</span><strong>{nextUnlock?new Date(`${nextUnlock.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{year:"numeric",month:"short",day:"numeric"}):"无已知固定事件"}</strong><small>{nextUnlock&&unlockSameDay?`${compact(unlockSameDay)} ${asset.name}${unlockRatio!=null?` · 当前流通量 ${unlockRatio.toFixed(1)}%`:""}`:"持续机制见下方说明"}</small></article><article><span>回购状态</span><strong>{asset.buybackStatus??"官方未披露"}</strong><small>回购、分配与销毁分开统计</small></article><article className={asset.burn30d!=null?"success":"neutral"}><span>30D 实际销毁</span><strong>{asset.burn30d==null?"官方未提供周期聚合":`${compact(asset.burn30d)} ${asset.name}`}</strong><small>{asset.burnPeriodSource??asset.burnedMethod}</small></article><article className={asset.burn90d!=null?"success":"neutral"}><span>90D 实际销毁</span><strong>{asset.burn90d==null?"官方未提供周期聚合":`${compact(asset.burn90d)} ${asset.name}`}</strong><small>缺失值不按 0 处理</small></article></section>
    <section className="dashboard-grid expanded-top-grid"><article className="panel expanded-price"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>{period} 价格趋势</h2></div><div className="period-switch">{(["30D","90D"] as const).map(value=><button type="button" className={period===value?"active":""} onClick={()=>setPeriod(value)} key={value}>{value}</button>)}</div></div><div className="price-summary"><strong>{asset.price==null?"—":money(asset.price,4)}</strong><span className={(chartChange??0)>=0?"positive":"negative"}>{chartChange==null?"—":`${chartChange>=0?"↑":"↓"} ${Math.abs(chartChange).toFixed(2)}%`}</span></div>{chart.length>1?<SnapshotChart data={chart} color={asset.color} label={`${asset.name} ${period} 价格趋势`}/>:<div className="chart-empty"><span className="fallback-dot"/>日线暂不可读</div>}<div className="chart-foot"><span>{chart[0]?new Date(chart[0][0]).toLocaleDateString("zh-CN",{month:"short",day:"numeric"}):"—"}</span><span>{asset.marketSource}</span><span>现在</span></div></article>
      <article className="panel expanded-supply"><div className="panel-head"><div><span className="section-kicker">SUPPLY BASIS</span><h2>供应与永久移除</h2></div></div><div className="expanded-ratio"><strong>{circulation==null?"—":`${circulation.toFixed(1)}%`}</strong><span>已流通 / 整体供应</span></div><div className="expanded-bar"><i style={{width:`${Math.min(100,circulation??0)}%`}}/></div><dl><div><dt>整体供应基准</dt><dd>{readable(asset.overallSupply,` ${asset.name}`)}</dd></div><div><dt>当前总供应</dt><dd>{readable(asset.totalSupply,` ${asset.name}`)}</dd></div><div><dt>已销毁 / 永久移除</dt><dd>{asset.burnedSupply==null?"官方未单列":`${compact(asset.burnedSupply)} ${asset.name}`}</dd></div><div><dt>30D / 90D 销毁</dt><dd>{asset.burn30d==null?"官方未提供周期聚合":`${compact(asset.burn30d)} / ${compact(asset.burn90d??0)} ${asset.name}`}</dd></div></dl><p className="micro-note">销毁口径：{asset.burnedMethod}</p></article></section>
    <section className="dashboard-grid expanded-lower-grid"><article className="panel expanded-staking"><div className="panel-head"><div><span className="section-kicker">TOKEN STAKING</span><h2>{asset.stakingLabel}</h2></div></div><div className="expanded-stake-value"><strong>{token==="xpl"?"尚未上线":!asset.stakingApplicable?"不适用":readable(asset.stakingAmount,` ${asset.name}`)}</strong><span>{token==="xpl"?"外部验证者与委托启用前，验证者通胀不会启动":!asset.stakingApplicable?"治理委托不构成代币质押":stakingRatio==null?"整体供应占比暂不可读":`${stakingRatio.toFixed(2)}% · 分母为整体供应`}</span></div><div className="expanded-bar"><i style={{width:`${Math.min(100,stakingRatio??0)}%`}}/></div><dl><div><dt>退出机制</dt><dd>{asset.stakingExit}</dd></div><div><dt>数据源</dt><dd>{asset.stakingSource}</dd></div></dl></article><article className="panel expanded-business"><div className="panel-head"><div><span className="section-kicker">PROTOCOL REFERENCE</span><h2>{asset.businessLabel}</h2></div></div><strong>{asset.businessValue==null?"暂不可读":money(asset.businessValue,0)}</strong><span>USD</span><p>{asset.valueCapture}</p><small>{asset.businessSource}</small></article><article className="panel expanded-risk"><div className="panel-head"><div><span className="section-kicker">WATCHLIST</span><h2>持续观察</h2></div></div><div><span>供应压力</span><strong>{asset.pressure}</strong></div><div><span>核心风险</span><strong>{asset.risk}</strong></div>{asset.unlockEvents?.length?<div className="expanded-unlock-list"><span>已知近期事件</span>{asset.unlockEvents.map(event=><strong key={`${event.date}-${event.label}`}>{event.date} · {compact(event.amount)} {asset.name} · {event.label}</strong>)}</div>:null}<p className="micro-note">缺失值不计作 0；业务参照不参与跨业务排名。</p></article></section>
    <footer className="expanded-footer"><strong>{asset.name} · Token Lens</strong><span>{loading?"正在刷新":"60 秒自动刷新"}</span></footer>
  </div>;
}
