"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency="usd";type Period="7D"|"30D"|"90D";
type HypeData={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;totalSupply:number;maxSupply:number;chart:Array<[number,number]>;chartSource:string;marketSource:string;protocol:{perpsVolume24h:number;spotVolume24h:number;openInterest:number;perpMarkets:number;source:string}|null;staking:{totalStaked:number;stakingRatio:number;activeValidators:number;totalValidators:number;weightedApr:number;top5Share:number;validators:Array<{validator:string;name:string;stake:number;commission:number;apr:number;uptime:number}>;delegationLockDays:number;withdrawalDays:number;source:string}|null;assistanceFund:{hype:number;address:string;source:string}|null;currencyRate:number;failedSources:string[];stale:boolean;updatedAt:string};
const compact=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money=(v:number,c:Currency,d=2)=>{void c;return new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v)};
const time=(v:string)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(v));
const date=(v:number)=>new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric"}).format(new Date(v));

function HypeChart({data}:{data:Array<[number,number]>}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas||data.length<2)return;const render=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p={top:18,right:12,bottom:18,left:12};canvas.width=Math.max(1,w*scale);canvas.height=Math.max(1,h*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);const values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1,pts=data.map((x,i)=>({x:p.left+i/(data.length-1)*(w-p.left-p.right),y:p.top+(max-x[1])/range*(h-p.top-p.bottom)}));ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(28,42,37,.09)";for(let i=0;i<4;i++){const y=p.top+i/3*(h-p.top-p.bottom);ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}const gradient=ctx.createLinearGradient(0,p.top,0,h);gradient.addColorStop(0,"rgba(83,218,164,.25)");gradient.addColorStop(1,"rgba(83,218,164,0)");ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.lineTo(pts.at(-1)!.x,h-p.bottom);ctx.lineTo(pts[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.strokeStyle="#35c98c";ctx.lineWidth=2.6;ctx.lineJoin="round";ctx.stroke();const last=pts.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,4,0,Math.PI*2);ctx.fillStyle="#15945f";ctx.fill()};render();const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect()},[data]);return <canvas ref={ref} className="hype-chart" aria-label="HYPE 价格趋势图"/>}
function Metric({label,value,meta,tone}:{label:string;value:string;meta:string;tone?:"positive"|"negative"|"warning"}){return <article className="metric-card hype-metric"><span className="metric-topline"><span>{label}</span><span className="arrow">↗</span></span><strong>{value}</strong><span className={`metric-meta ${tone||""}`}>{meta}</span></article>}

export default function HypeDashboard({currency,refreshNonce=0}:{currency:Currency;refreshNonce?:number}){
  const [data,setData]=useState<HypeData|null>(null),[error,setError]=useState<string|null>(null),[period,setPeriod]=useState<Period>("30D");
  const load=useCallback(async()=>{setError(null);try{const response=await fetch(`/api/hype?currency=${currency}&t=${Date.now()}`);if(!response.ok)throw new Error("HYPE 实时数据暂时不可用");setData(await response.json())}catch(reason){setData(null);setError(reason instanceof Error?reason.message:"HYPE 数据暂时不可用")}},[currency]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,30_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const chart=useMemo(()=>{if(!data)return[];const days=period==="7D"?7:period==="30D"?30:90;return data.chart.slice(-days)},[data,period]);
  if(!data)return <section className="bp-loading hype-loading" aria-live="polite"><div><span className={error?"fallback-dot":"live-dot"}/><strong>{error||"正在连接 HYPE 行情与 Hyperliquid 官方数据"}</strong><small>{error?"不会用旧数字冒充实时结果":"行情、交易业务、质押和援助基金同时载入"}</small>{error?<button type="button" onClick={load}>重新获取</button>:null}</div><div className="loading-metrics">{Array.from({length:6},(_,i)=><i key={i}/>)}</div><div className="loading-panels"><i/><i/><i/></div></section>;
  const start=chart[0]?.[1]??data.price,periodChange=start>0?(data.price/start-1)*100:0,p=data.protocol,s=data.staking,fund=data.assistanceFund,turnover=data.marketCap>0?data.volume24h/data.marketCap*100:0,oiRatio=p&&p.perpsVolume24h>0?p.openInterest/p.perpsVolume24h:0;
  const signals=[
    {label:"市场",title:periodChange>=0?`${period} 价格保持正动能`:`${period} 价格仍在回撤`,detail:`24H ${data.change24h>=0?"+":""}${data.change24h.toFixed(2)}% · 换手率 ${turnover.toFixed(1)}%`,tone:periodChange>=0?"tone-positive":"tone-negative"},
    {label:"交易业务",title:p?`永续 24H ${money(p.perpsVolume24h,currency,0)}`:"交易业务暂不可读",detail:p?`未平仓 ${money(p.openInterest,currency,0)} · OI/成交量 ${(oiRatio*100).toFixed(1)}%`:"行情与质押模块继续显示",tone:p?"tone-positive":"tone-neutral"},
    {label:"价值回流",title:fund?`${compact(fund.hype)} HYPE 位于援助基金` :"援助基金余额暂不可读",detail:"官方机制将援助基金获得的 HYPE 从流通及总供应口径移除",tone:fund?"tone-positive":"tone-neutral"},
    {label:"网络安全",title:s?`${compact(s.totalStaked)} HYPE 已质押`:"质押数据暂不可读",detail:s?`${s.activeValidators} 个活跃验证者 · Top 5 占 ${(s.top5Share*100).toFixed(1)}%`:"不估算质押率或 APR",tone:s&&s.top5Share>.5?"tone-warning":"tone-positive"}
  ];
  return <div className="hype-dashboard">
    <section className="metrics-grid" aria-label="HYPE 关键指标"><Metric label="HYPE 当前价格" value={money(data.price,currency,4)} meta={`${data.change24h>=0?"+":""}${data.change24h.toFixed(2)}% · ${data.marketSource}`} tone={data.change24h>=0?"positive":"negative"}/><Metric label="流通市值" value={money(data.marketCap,currency,0)} meta={`FDV ${money(data.fdv,currency,0)}`}/><Metric label="24H 永续成交" value={p?money(p.perpsVolume24h,currency,0):"暂不可读"} meta={p?`${p.perpMarkets} 个永续市场` :"Hyperliquid Info API"}/><Metric label="未平仓量 OI" value={p?money(p.openInterest,currency,0):"暂不可读"} meta={p?`${(oiRatio*100).toFixed(1)}% / 24H永续量`:"不使用估算值"}/><Metric label="HYPE 已质押" value={s?`${compact(s.totalStaked)} HYPE`:"暂不可读"} meta={s?`${(s.stakingRatio*100).toFixed(2)}% 最大供应 · APR ${(s.weightedApr*100).toFixed(2)}%`:"官方验证者数据"}/><Metric label="援助基金 HYPE" value={fund?compact(fund.hype):"暂不可读"} meta="官方回购与供应移除机制" tone="warning"/></section>
    <nav className="bp-section-nav hype-section-nav" aria-label="HYPE 页面导航"><a href="#hype-overview">总览</a><a href="#hype-market">市场</a><a href="#hype-business">交易业务</a><a href="#hype-staking">质押</a><a href="#hype-value">价值回流</a></nav>
    <section className="signal-board hype-signal-board" id="hype-overview"><div className="signal-board-head"><div><span className="section-kicker">HYPE AUTOMATED BRIEF</span><h1>{p&&s&&fund?"交易收入、价值回流与网络安全，要放在一起看。":"部分官方数据源暂不可用，保留可验证模块。"}</h1></div><p>基于交易所行情、Hyperliquid 全市场成交与 OI、验证者质押和 Assistance Fund 余额自动生成。</p><em><i className={data.stale?"fallback-dot":"live-dot"}/>{data.stale?"部分源异常":"实时规则引擎"} · {time(data.updatedAt)}</em></div><div className="signal-grid">{signals.map(x=><article className={`signal-card ${x.tone}`} key={x.label}><span>{x.label}</span><strong>{x.title}</strong><p>{x.detail}</p></article>)}</div></section>
    <section className="dashboard-grid hype-top-grid" id="hype-market"><article className="panel"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(v=><button type="button" className={period===v?"active":""} onClick={()=>setPeriod(v)} key={v}>{v}</button>)}</div></div><div className="price-summary"><strong>{money(data.price,currency,4)}</strong><span className={periodChange>=0?"positive":"negative"}>{periodChange>=0?"↑":"↓"} {Math.abs(periodChange).toFixed(2)}%</span></div>{chart.length>1?<HypeChart data={chart}/>:<div className="bp-chart-empty"><span className="fallback-dot"/>K 线暂不可读</div>}<div className="chart-foot"><span>{chart[0]?date(chart[0][0]):"—"}</span><span>K 线 · {data.chartSource}　报价 · {data.marketSource}</span><span>现在</span></div></article>
      <article className="panel hype-business-panel" id="hype-business"><div className="panel-head"><div><span className="section-kicker">EXCHANGE ENGINE</span><h2>交易业务快照</h2></div><a className="text-button" href="https://app.hyperliquid.xyz/trade" target="_blank" rel="noreferrer">官方交易页 ↗</a></div>{p?<><div className="hype-business-grid"><div><span>永续成交额 · 24H</span><strong>{money(p.perpsVolume24h,currency,0)}</strong><small>{p.perpMarkets} 个市场</small></div><div><span>现货成交额 · 24H</span><strong>{money(p.spotVolume24h,currency,0)}</strong><small>HyperCore 现货</small></div><div><span>未平仓量</span><strong>{money(p.openInterest,currency,0)}</strong><small>{(oiRatio*100).toFixed(1)}% / 永续成交</small></div></div><p className="micro-note">{p.source} · 全市场上下文聚合，不把外部交易所 HYPE 成交计入协议业务。</p></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>交易业务暂不可读</strong></div>}</article></section>
    <section className="dashboard-grid hype-lower-grid"><article className="panel hype-staking-panel" id="hype-staking"><div className="panel-head"><div><span className="section-kicker">HYPERBFT SECURITY</span><h2>质押与验证者</h2></div><a className="text-button" href="https://app.hyperliquid.xyz/staking" target="_blank" rel="noreferrer">官方质押页 ↗</a></div>{s?<><div className="hype-stake-hero"><div><span>活跃质押</span><strong>{compact(s.totalStaked)} HYPE</strong><small>{s.activeValidators} / {s.totalValidators} 验证者活跃</small></div><div><span>加权预测 APR</span><strong>{(s.weightedApr*100).toFixed(2)}%</strong><small>按活跃验证者质押加权</small></div><div><span>Top 5 集中度</span><strong>{(s.top5Share*100).toFixed(1)}%</strong><small>占活跃质押</small></div></div><div className="hype-exit-flow"><span><b>委托</b><small>进入验证者</small></span><i>→</i><span><b>{s.delegationLockDays} 天</b><small>委托锁定</small></span><i>→</i><span><b>解除委托</b><small>回到质押账户</small></span><i>→</i><span><b>{s.withdrawalDays} 天</b><small>转回现货账户</small></span></div><div className="hype-validator-list">{s.validators.slice(0,6).map((v,index)=><div key={v.validator}><span><i>{index+1}</i><b>{v.name}</b></span><strong>{compact(v.stake)} HYPE</strong><small>APR {(v.apr*100).toFixed(2)}% · 佣金 {(v.commission*100).toFixed(1)}%</small></div>)}</div></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>质押数据暂不可读</strong></div>}</article>
      <article className="panel hype-value-panel" id="hype-value"><div className="panel-head"><div><span className="section-kicker">VALUE RETURN</span><h2>回购与供应口径</h2></div></div>{fund?<><div className="hype-fund-hero"><span>Assistance Fund 持有</span><strong>{compact(fund.hype)} HYPE</strong><small>{money(fund.hype*data.price,currency,0)} · 当前价格折算</small></div><div className="hype-mechanism"><span className="live-dot"/><p><strong>官方费用机制：</strong>援助基金自动将交易费用转换为 HYPE；基金中的 HYPE 从流通量与总供应量中移除。</p></div></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>援助基金余额暂不可读</strong></div>}<div className="hype-supply-list"><div><span>流通供应</span><strong>{compact(data.circulatingSupply)} HYPE</strong></div><div><span>总供应</span><strong>{compact(data.totalSupply)} HYPE</strong></div><div><span>最大供应</span><strong>{compact(data.maxSupply)} HYPE</strong></div><div><span>流通率</span><strong>{data.maxSupply>0?(data.circulatingSupply/data.maxSupply*100).toFixed(1):"—"}%</strong></div></div><p className="micro-note">不把基金余额等同于某一期间回购量，也不估算累计手续费；供应采用市场数据口径。</p></article></section>
    <footer className="hype-footer"><div><span className="brand-mark small">h</span><strong>HYPE lens</strong></div><p>交易量、OI、质押 APR 与基金余额持续变化；数据用于研究，不构成投资建议。</p><div><a href="https://hyperliquid.xyz/" target="_blank" rel="noreferrer">Hyperliquid 官网 ↗</a><a href="https://hyperliquid.gitbook.io/hyperliquid-docs" target="_blank" rel="noreferrer">官方文档 ↗</a></div></footer>
  </div>;
}
