"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency = "usd" | "cny";
type Period = "7D" | "30D" | "90D";
type DetailKey = "price" | "supply" | "staking" | "unlock" | "buyback" | "volume" | null;
type Venue = { name:string; price:number; change24h:number; volume24h:number; high24h:number; low24h:number };
type MarketData = { price:number; change24h:number; marketCap:number; fdv:number; volume24h:number; circulatingSupply:number; totalSupply:number; high24h:number; low24h:number; ath:number; athDate:string; chart:Array<[number,number]>; chartSource:string; venues:Venue[]; volumeScope:string; circulatingSource:string; fxSource:string; source:string; stale:boolean; updatedAt:string };
type ChainRow = { name:string; shares:number; rate:number; staked:number; pendingShares:number; pending:number; pendingAvailable:boolean; withdrawEnabled:boolean; withdrawDelay:number; completionWindow:number; tokenSupply:number; blockNumber:number; ok:boolean };
type ChainData = { ethfiSupply:number; mainnetSupply:number; supplyAdjustment:number; burned:number; burnStatus:string; totalShares:number; exchangeRate:number; staked:number; pendingShares:number; pending:number; pendingCoverage:string[]; pendingComplete:boolean; withdrawDelay:number; completionWindow:number; pendingLabel:string; chains:ChainRow[]; source:string; stale:boolean; updatedAt:string };
type StakingHistory = { points:Array<[number,number,number]>; rangeDays:number; chains:string[]; source:string; method:string; updatedAt:string };

const unlocks = [
  {date:"2026-09-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2026-10-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2026-11-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2026-12-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2027-01-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2027-02-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2027-03-15",amount:8_945_833,group:"核心贡献者与投资人"},
];
const allocation = [
  {label:"投资人",value:33.74,color:"#181b1a"},{label:"生态金库",value:21.62,color:"#2f6f5e"},{label:"核心贡献者",value:21.47,color:"#87ae9f"},
  {label:"用户空投",value:19.27,color:"#dfab57"},{label:"合作与流动性",value:3.9,color:"#e8e4db"},
];

const compact = (v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money = (v:number,c:Currency,d=2)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c.toUpperCase(),minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const fullNumber = (v:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:0}).format(v);
const daysUntil = (date:string,now:number)=>Math.max(0,Math.ceil((new Date(`${date}T00:00:00+08:00`).getTime()-now)/86_400_000));
const formatTime = (value:string)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value));

function TrendChart({data,positive,label="ETHFI 价格趋势图",className="trend-canvas"}:{data:Array<[number,number]>;positive:boolean;label?:string;className?:string}) {
  const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=canvasRef.current; if(!canvas||data.length<2)return;
    const render=()=>{
      const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1;
      canvas.width=Math.max(1,box.width*scale); canvas.height=Math.max(1,box.height*scale);
      const ctx=canvas.getContext("2d"); if(!ctx)return; ctx.scale(scale,scale);
      const w=box.width,h=box.height,p={top:20,right:10,bottom:22,left:10},values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;
      const color=positive?"#277a63":"#b45a43"; ctx.clearRect(0,0,w,h); ctx.strokeStyle="rgba(24,27,26,.08)"; ctx.lineWidth=1;
      for(let i=0;i<4;i++){const y=p.top+((h-p.top-p.bottom)/3)*i;ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}
      const pts=data.map((x,i)=>({x:p.left+(i/(data.length-1))*(w-p.left-p.right),y:p.top+((max-x[1])/range)*(h-p.top-p.bottom)}));
      const gradient=ctx.createLinearGradient(0,p.top,0,h);gradient.addColorStop(0,positive?"rgba(39,122,99,.22)":"rgba(180,90,67,.18)");gradient.addColorStop(1,"rgba(255,255,255,0)");
      ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.lineTo(pts.at(-1)!.x,h-p.bottom);ctx.lineTo(pts[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();
      ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.lineJoin="round";ctx.stroke();
      const last=pts.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();
    }; render(); const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect();
  },[data,positive]);
  return <canvas ref={canvasRef} className={className} aria-label={label}/>;
}

function MetricCard({eyebrow,value,meta,tone,onClick}:{eyebrow:string;value:string;meta:string;tone?:"positive"|"negative"|"warning";onClick:()=>void}){
  return <button className="metric-card" onClick={onClick} type="button"><span className="metric-topline"><span>{eyebrow}</span><span className="arrow">↗</span></span><strong>{value}</strong><span className={`metric-meta ${tone||""}`}>{meta}</span></button>;
}

function DashboardLoading({error,onRetry}:{error:string|null;onRetry:()=>void}){
  return <section className="dashboard-loading" aria-live="polite"><div className="loading-head"><span className={error?"fallback-dot":"live-dot"}/><div><strong>{error||"正在获取实时数据"}</strong><small>{error?"不会显示缓存或默认数字":"行情、供应和四链合约将同时载入"}</small></div>{error&&<button type="button" onClick={onRetry}>重新获取</button>}</div><div className="loading-metrics">{Array.from({length:6},(_,i)=><i key={i}/>)}</div><div className="loading-panels"><i/><i/><i/></div></section>;
}

function DetailDrawer({active,onClose,market,chain,currency}:{active:DetailKey;onClose:()=>void;market:MarketData;chain:ChainData;currency:Currency}){
  useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  if(!active)return null;
  const content:Record<Exclude<DetailKey,null>,{title:string;kicker:string;body:React.ReactNode}>={
    price:{title:"价格与估值",kicker:"Market overview",body:<><div className="drawer-hero"><span>三所现货中位价</span><strong>{money(market.price,currency,4)}</strong><em className={market.change24h>=0?"positive":"negative"}>{market.change24h>=0?"+":""}{market.change24h.toFixed(2)}% · 24H</em></div><div className="chain-list">{market.venues.map(item=><div className="chain-row" key={item.name}><span className="chain-name"><i className="live-dot"/>{item.name}</span><span>{money(item.price,currency,4)}</span><span>{item.change24h>=0?"+":""}{item.change24h.toFixed(2)}%</span></div>)}</div><div className="detail-grid"><div><span>24H 最高</span><strong>{money(market.high24h,currency,4)}</strong></div><div><span>24H 最低</span><strong>{money(market.low24h,currency,4)}</strong></div><div><span>流通市值</span><strong>{money(market.marketCap,currency,0)}</strong></div><div><span>完全稀释估值</span><strong>{money(market.fdv,currency,0)}</strong></div><div><span>历史最高</span><strong>{money(market.ath,currency,2)}</strong></div><div><span>距历史高点</span><strong>{((market.price/market.ath-1)*100).toFixed(1)}%</strong></div></div><p className="drawer-note">价格取 Binance、OKX、Bybit 有效报价的中位数，避免单一交易所瞬时异常。</p></>},
    supply:{title:"供应与流通",kicker:"Supply intelligence",body:<><div className="drawer-hero"><span>当前流通率</span><strong>{(market.circulatingSupply/chain.ethfiSupply*100).toFixed(2)}%</strong><em>{compact(market.circulatingSupply)} / {compact(chain.ethfiSupply)} ETHFI</em></div><div className="supply-bar large"><i style={{width:`${Math.min(100,market.circulatingSupply/chain.ethfiSupply*100)}%`}}/></div><div className="detail-grid"><div><span>固定最大供应</span><strong>{fullNumber(chain.ethfiSupply)}</strong></div><div><span>市场流通量</span><strong>{fullNumber(market.circulatingSupply)}</strong></div><div><span>未流通</span><strong>{fullNumber(Math.max(0,chain.ethfiSupply-market.circulatingSupply))}</strong></div><div><span>官方确认销毁</span><strong>{fullNumber(chain.burned)}</strong></div><div><span>以太坊主网供应</span><strong>{fullNumber(chain.mainnetSupply)}</strong></div><div><span>主网供应差额</span><strong>{fullNumber(chain.supplyAdjustment)}</strong></div></div><p className="drawer-note">流通口径：{market.circulatingSource}。主网供应差额包含跨链桥铸造/锁定等影响，不能直接算作销毁。</p></>},
    staking:{title:"sETHFI 质押与退出",kicker:"Staking / unstaking",body:<><div className="drawer-hero"><span>四链 sETHFI 对应的质押资产</span><strong>{compact(chain.staked)} ETHFI</strong><em>1 sETHFI = {chain.exchangeRate.toFixed(6)} ETHFI</em></div><div className="detail-grid"><div><span>sETHFI 总份额</span><strong>{fullNumber(chain.totalShares)}</strong></div><div><span>对应 ETHFI</span><strong>{fullNumber(chain.staked)}</strong></div><div><span>已覆盖退出队列</span><strong>{fullNumber(chain.pendingShares)}</strong></div><div><span>已覆盖待赎回</span><strong>{fullNumber(chain.pending)}</strong></div><div><span>退出等待期</span><strong>{Math.round(chain.withdrawDelay/86_400)} 天</strong></div><div><span>完成窗口</span><strong>{Math.round(chain.completionWindow/86_400)} 天</strong></div></div><div className="chain-list">{chain.chains.map(item=><div className="chain-row" key={item.name}><span className="chain-name"><i className={item.ok?"live-dot":"fallback-dot"}/>{item.name}</span><span>{compact(item.shares)} sETHFI</span><span>{item.pendingAvailable?`${compact(item.pendingShares)} 排队`:"队列未覆盖"}</span></div>)}</div><p className="drawer-note">质押总量覆盖 Ethereum、Optimism、Arbitrum、Base。退出队列直接读取 DelayedWithdraw 的 outstandingShares 与 viewOutstandingDebt，目前覆盖 {chain.pendingCoverage.join("、")}；未覆盖的链不会用 0 冒充。</p></>},
    unlock:{title:"代币归属解锁",kicker:"Token vesting unlock",body:<><div className="drawer-hero"><span>非质押退出 · 剩余公开排期</span><strong>{compact(unlocks.reduce((s,x)=>s+x.amount,0))} ETHFI</strong><em>团队 / 投资人归属释放，预计至 2027 年 3 月</em></div><div className="unlock-list full">{unlocks.map((item,index)=><div className="unlock-row" key={item.date}><span className="unlock-index">{String(index+1).padStart(2,"0")}</span><div><strong>{new Date(`${item.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"})}</strong><small>{item.group}</small></div><div className="unlock-amount"><strong>{compact(item.amount)}</strong><small>{(item.amount/market.totalSupply*100).toFixed(2)}% 总供应</small></div></div>)}</div><p className="drawer-note">这是 Tokenomics.com 校验的代币归属排期，不是 sETHFI 解押。页面按当前日期自动定位下一事件；实际进入市场仍取决于接收钱包动作。</p></>},
    buyback:{title:"回购与销毁",kicker:"Protocol value flow",body:<><div className="drawer-hero"><span>官方确认销毁</span><strong>{compact(chain.burned)} ETHFI</strong><em>当前机制：未启用销毁</em></div><div className="flow-stack"><div><b>01</b><span><strong>协议收入</strong><small>提现费与部分协议收入</small></span></div><div><b>02</b><span><strong>市场回购</strong><small>周度与月度执行</small></span></div><div><b>03</b><span><strong>分配给 sETHFI</strong><small>增加质押参与者价值</small></span></div></div><div className="notice"><strong>回购 ≠ 销毁</strong><p>{chain.burnStatus}。只有代币进入不可恢复地址或总供应明确永久减少，才计入销毁。</p></div></>},
    volume:{title:"交易与流动性",kicker:"Market activity",body:<><div className="drawer-hero"><span>24H 三所现货成交额</span><strong>{money(market.volume24h,currency,0)}</strong><em>成交额 / 市值 {(market.volume24h/market.marketCap*100).toFixed(1)}%</em></div><div className="detail-grid"><div><span>流通市值</span><strong>{money(market.marketCap,currency,0)}</strong></div><div><span>FDV</span><strong>{money(market.fdv,currency,0)}</strong></div><div><span>流通率</span><strong>{(market.circulatingSupply/market.totalSupply*100).toFixed(1)}%</strong></div><div><span>24H 振幅</span><strong>{((market.high24h-market.low24h)/market.low24h*100).toFixed(1)}%</strong></div></div><p className="drawer-note">口径：{market.volumeScope}。不包含其他 CEX、DEX 或链上 Transfer，因此不会误标成“全市场成交额”。</p></>},
  };
  const current=content[active];
  return <div className="drawer-layer" role="dialog" aria-modal="true" aria-label={current.title}><button className="drawer-backdrop" onClick={onClose} aria-label="关闭详情"/><aside className="detail-drawer"><div className="drawer-head"><div><span>{current.kicker}</span><h2>{current.title}</h2></div><button type="button" onClick={onClose} aria-label="关闭">×</button></div><div className="drawer-body">{current.body}</div><div className="drawer-source"><span className={market.stale||chain.stale?"fallback-dot":"live-dot"}/> 数据更新于 {formatTime(active==="price"||active==="volume"?market.updatedAt:chain.updatedAt)}</div></aside></div>;
}

export default function Home(){
  const [market,setMarket]=useState<MarketData|null>(null),[chain,setChain]=useState<ChainData|null>(null),[stakingHistory,setStakingHistory]=useState<StakingHistory|null>(null),[currency,setCurrency]=useState<Currency>("usd"),[period,setPeriod]=useState<Period>("30D"),[stakingPeriod,setStakingPeriod]=useState<Period>("30D"),[detail,setDetail]=useState<DetailKey>(null),[refreshing,setRefreshing]=useState(true),[loadError,setLoadError]=useState<string|null>(null),[historyLoading,setHistoryLoading]=useState(true);
  const loadData=useCallback(async(force=false)=>{setRefreshing(true);setLoadError(null);if(force){setMarket(null);setChain(null)}const suffix=force?`&refresh=${Date.now()}`:"";try{const [m,c]=await Promise.allSettled([fetch(`/api/market?currency=${currency}${suffix}`).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`/api/chain?${force?`refresh=${Date.now()}`:"source=auto"}`).then(r=>{if(!r.ok)throw new Error();return r.json()})]);if(m.status==="fulfilled")setMarket(m.value);if(c.status==="fulfilled")setChain(c.value);if(m.status==="rejected"||c.status==="rejected")setLoadError("部分实时数据暂时不可用")}finally{setRefreshing(false)}},[currency]);
  const loadHistory=useCallback(async(force=false)=>{if(force)setStakingHistory(null);setHistoryLoading(true);try{const response=await fetch(`/api/staking-history?${force?`refresh=${Date.now()}`:"source=auto"}`);if(!response.ok)throw new Error();setStakingHistory(await response.json())}catch{setStakingHistory(null)}finally{setHistoryLoading(false)}},[]);
  useEffect(()=>{const initial=window.setTimeout(()=>loadData(),0),timer=window.setInterval(()=>loadData(),30_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[loadData]);
  useEffect(()=>{const initial=window.setTimeout(()=>loadHistory(),0),timer=window.setInterval(()=>loadHistory(),900_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[loadHistory]);
  const referenceTime=market&&chain?Math.max(new Date(market.updatedAt).getTime(),new Date(chain.updatedAt).getTime()):0;
  const filteredChart=useMemo(()=>{if(!market)return[];const wanted=period==="7D"?7:period==="30D"?30:90,threshold=referenceTime-wanted*86_400_000,selected=market.chart.filter(x=>x[0]>=threshold);return selected.length>1?selected:market.chart.slice(-wanted)},[market,period,referenceTime]);
  const filteredStaking=useMemo(()=>{if(!stakingHistory||!chain)return[];const wanted=stakingPeriod==="7D"?7:stakingPeriod==="30D"?30:90,threshold=referenceTime-wanted*86_400_000,selected=stakingHistory.points.filter(x=>x[0]>=threshold).map(x=>[x[0],x[2]] as [number,number]);if(selected.length){selected[selected.length-1]=[referenceTime,chain.staked]}return selected},[stakingHistory,chain,stakingPeriod,referenceTime]);
  const nextUnlock=unlocks.find(x=>new Date(`${x.date}T23:59:59+08:00`).getTime()>referenceTime)||unlocks.at(-1)!;
  const nonCirculating=market&&chain?Math.max(0,chain.ethfiSupply-market.circulatingSupply):0,circulatingPct=market&&chain?Math.min(100,market.circulatingSupply/chain.ethfiSupply*100):0,chartPositive=filteredChart.length>1&&filteredChart.at(-1)![1]>=filteredChart[0][1],stakingPositive=filteredStaking.length>1&&filteredStaking.at(-1)![1]>=filteredStaking[0][1],stakingChange=filteredStaking.length>1?(filteredStaking.at(-1)![1]-filteredStaking[0][1]):0;
  const donut=`conic-gradient(${allocation.map((item,index)=>{const start=allocation.slice(0,index).reduce((s,x)=>s+x.value,0);return `${item.color} ${start}% ${start+item.value}%`}).join(",")})`;
  return <div className="app-shell">
    <main><header className="topbar"><div className="top-identity"><a className="brand" href="#overview" aria-label="ETHFI Lens 首页"><span className="brand-mark small">e</span><span>ETHFI<span>lens</span></span></a><div className="breadcrumb"><b>/</b><strong>实时数据总览</strong></div></div><div className="top-actions"><span className={!market||!chain||market.stale||chain.stale?"fallback-dot":"live-dot"}/><span className="updated">{market&&chain?`${market.stale||chain.stale?"部分源异常":"实时源正常"} · ${formatTime(market.updatedAt)}`:"正在获取实时数据"}</span><div className="currency-switch" aria-label="计价币种"><button type="button" className={currency==="usd"?"active":""} onClick={()=>{if(currency!=="usd"){setMarket(null);setCurrency("usd")}}}>USD</button><button type="button" className={currency==="cny"?"active":""} onClick={()=>{if(currency!=="cny"){setMarket(null);setCurrency("cny")}}}>CNY</button></div><button className={`refresh-button ${refreshing?"loading":""}`} type="button" onClick={()=>{loadData(true);loadHistory(true)}} disabled={refreshing}><span>↻</span>{refreshing?"刷新中":"刷新数据"}</button></div></header>
      <div className="content">
        <section className="hero" id="overview"><div><span className="section-kicker">ETHER.FI TOKEN INTELLIGENCE</span><h1>看懂 ETHFI，<br/><em>不只看价格。</em></h1><p>市场、供应、质押与解锁信号，汇总在一个干净的视图里。</p></div><div className="hero-token"><div className="token-orbit"><span>ETHFI</span></div><div><small>官方合约</small><strong>0xfe0c...cc0eb</strong><a href="https://etherscan.io/token/0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb" target="_blank" rel="noreferrer">在 Etherscan 验证 ↗</a></div></div></section>
        {market&&chain?<>
        <section className="metrics-grid" aria-label="关键指标"><MetricCard eyebrow="当前价格" value={money(market.price,currency,4)} meta={`${market.change24h>=0?"+":""}${market.change24h.toFixed(2)}% · 三所中位价`} tone={market.change24h>=0?"positive":"negative"} onClick={()=>setDetail("price")}/><MetricCard eyebrow="流通市值" value={money(market.marketCap,currency,0)} meta={`FDV ${money(market.fdv,currency,0)}`} onClick={()=>setDetail("price")}/><MetricCard eyebrow="24H 三所现货量" value={money(market.volume24h,currency,0)} meta={`${(market.volume24h/market.marketCap*100).toFixed(1)}% 成交额/市值`} onClick={()=>setDetail("volume")}/><MetricCard eyebrow="流通供应" value={`${compact(market.circulatingSupply)} ETHFI`} meta={`${circulatingPct.toFixed(2)}% 总供应`} tone="positive" onClick={()=>setDetail("supply")}/><MetricCard eyebrow="sETHFI 质押" value={`${compact(chain.staked)} ETHFI`} meta={`${compact(chain.totalShares)} sETHFI`} onClick={()=>setDetail("staking")}/><MetricCard eyebrow="下次代币归属解锁" value={`${daysUntil(nextUnlock.date,referenceTime)} 天`} meta={`${compact(nextUnlock.amount)} ETHFI · 非质押退出`} tone="warning" onClick={()=>setDetail("unlock")}/></section>
        <section className="dashboard-grid" id="market"><article className="panel price-panel"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(x=><button type="button" className={period===x?"active":""} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div></div><div className="price-summary"><strong>{money(market.price,currency,4)}</strong><span className={chartPositive?"positive":"negative"}>{chartPositive?"↑":"↓"} {Math.abs((filteredChart.at(-1)?.[1]/filteredChart[0]?.[1]-1)*100||0).toFixed(2)}%</span></div>{filteredChart.length>1?<TrendChart data={filteredChart} positive={chartPositive}/>:<div className="chart-empty"><span className="fallback-dot"/>正在切换备用 K 线源…</div>}<div className="chart-foot"><span>{new Date(filteredChart[0]?.[0]||referenceTime).toLocaleDateString("zh-CN",{month:"short",day:"numeric"})}</span><span>K 线 · {market.chartSource}　报价 · {market.source}</span><span>现在</span></div></article>
          <article className="panel supply-panel" id="supply"><div className="panel-head"><div><span className="section-kicker">TOKEN SUPPLY</span><h2>供应状态</h2></div><button className="text-button" type="button" onClick={()=>setDetail("supply")}>查看详情 ↗</button></div><div className="supply-main"><div><span>已流通</span><strong>{circulatingPct.toFixed(2)}%</strong></div><div className="supply-ring" style={{"--progress":`${circulatingPct*3.6}deg`} as React.CSSProperties}><span>{compact(market.circulatingSupply)}</span><small>ETHFI</small></div></div><div className="supply-bar"><i style={{width:`${circulatingPct}%`}}/></div><div className="supply-legend"><div><i className="circulating"/><span>流通</span><strong>{compact(market.circulatingSupply)}</strong></div><div><i className="locked"/><span>未流通</span><strong>{compact(nonCirculating)}</strong></div><div><i className="burned"/><span>已销毁</span><strong>{compact(chain.burned)}</strong></div></div><p className="micro-note">固定供应 10 亿枚 · 未流通不等于未解锁</p></article></section>
        <section className="dashboard-grid lower-grid"><article className="panel staking-panel" id="staking"><div className="panel-head"><div><span className="section-kicker">SETHFI STAKING</span><h2>质押历史与退出队列</h2></div><button className="text-button" type="button" onClick={()=>setDetail("staking")}>合约明细 ↗</button></div><div className="stake-flow"><div><small>存入</small><strong>ETHFI</strong></div><i>→</i><div><small>获得份额</small><strong>sETHFI</strong></div><i>→</i><div><small>已覆盖退出队列</small><strong>{compact(chain.pendingShares)}</strong></div></div><div className="staking-totals"><div><span>四链 sETHFI 总份额</span><strong>{compact(chain.totalShares)}</strong><small>sETHFI</small></div><div><span>对应质押资产</span><strong>{compact(chain.staked)}</strong><small>ETHFI</small></div></div><div className="staking-history-head"><div><span>{stakingPeriod} 净变化</span><strong className={stakingPositive?"positive":"negative"}>{stakingChange>=0?"+":""}{compact(stakingChange)} ETHFI</strong></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(x=><button type="button" className={stakingPeriod===x?"active":""} onClick={()=>setStakingPeriod(x)} key={x}>{x}</button>)}</div></div>{filteredStaking.length>1?<><TrendChart data={filteredStaking} positive={stakingPositive} label="sETHFI 对应质押资产历史趋势图" className="stake-trend-canvas"/><div className="stake-chart-foot"><span>{new Date(filteredStaking[0][0]).toLocaleDateString("zh-CN",{month:"short",day:"numeric"})}</span><span>链上日快照 · 现在</span></div></>:<div className="stake-chart-empty"><span className="fallback-dot"/>{historyLoading?"正在回填链上历史…":"历史曲线暂不可用，当前值仍为实时链上数据"}</div>}<div className="chain-chips">{chain.chains.map(x=><span key={x.name}><i className={x.ok?"live-dot":"fallback-dot"}/>{x.name}<b>{compact(x.shares)} sETHFI</b></span>)}</div><div className="insight"><span>退出队列覆盖 · {chain.pendingCoverage.join(" / ")}</span><p>当前已覆盖队列为 {compact(chain.pendingShares)} sETHFI；历史曲线按四链铸造/销毁净额与当日兑换率重建，不使用默认数字。</p></div></article>
          <article className="panel unlock-panel" id="unlocks"><div className="panel-head"><div><span className="section-kicker">TOKEN VESTING</span><h2>代币归属解锁</h2></div><button className="text-button" type="button" onClick={()=>setDetail("unlock")}>完整日历 ↗</button></div><div className="scope-badge">非 sETHFI 解押</div><div className="unlock-callout"><div><span>下一归属释放</span><strong>{new Date(`${nextUnlock.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{month:"long",day:"numeric"})}</strong><small>{nextUnlock.group}</small></div><div><strong>{compact(nextUnlock.amount)}</strong><small>ETHFI · {(nextUnlock.amount/market.totalSupply*100).toFixed(2)}%</small></div></div><div className="timeline"><i/><span className="today" style={{left:"12%"}}><b>今天</b></span>{unlocks.slice(0,4).map((x,i)=><span className="event" style={{left:`${28+i*21}%`}} key={x.date}><b>{new Date(`${x.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"})}</b></span>)}</div><div className="unlock-risk"><span className="warning-dot"/><p>未来 30 天预计归属释放 <strong>{compact(nextUnlock.amount)} ETHFI</strong>，约为流通量的 {(nextUnlock.amount/market.circulatingSupply*100).toFixed(2)}%。</p></div></article>
          <article className="panel allocation-panel"><div className="panel-head"><div><span className="section-kicker">ALLOCATION</span><h2>代币分配</h2></div></div><div className="allocation-content"><div className="donut" style={{background:donut}}><span><strong>1B</strong><small>总供应</small></span></div><div className="allocation-list">{allocation.map(x=><div key={x.label}><i style={{background:x.color}}/><span>{x.label}</span><strong>{x.value}%</strong></div>)}</div></div></article></section>
        <section className="activity-strip"><div><span className="section-kicker">PROTOCOL ACTIONS</span><h2>回购、分配与销毁，要分开看。</h2></div><div className="action-cards"><button type="button" onClick={()=>setDetail("buyback")}><span>回购机制</span><strong>周度 + 月度</strong><small>协议收入驱动 ↗</small></button><button type="button" onClick={()=>setDetail("buyback")}><span>主要去向</span><strong>sETHFI 持有人</strong><small>价值再分配 ↗</small></button><button type="button" onClick={()=>setDetail("buyback")}><span>官方确认销毁</span><strong>{compact(chain.burned)} ETHFI</strong><small>当前未启用销毁 ↗</small></button></div></section>
        <footer><div><span className="brand-mark small">e</span><strong>ETHFI lens</strong></div><p>数据用于研究与观察，不构成投资建议。</p><div><a href="https://etherfi.gitbook.io/gov/ethfi-allocations" target="_blank" rel="noreferrer">官方代币经济 ↗</a><a href="https://etherfi.gitbook.io/etherfi/ethfi/ethfi-staking" target="_blank" rel="noreferrer">质押文档 ↗</a></div></footer>
        </>:<DashboardLoading error={loadError} onRetry={()=>loadData(true)}/>}
      </div></main>
    {market&&chain&&<DetailDrawer active={detail} onClose={()=>setDetail(null)} market={market} chain={chain} currency={currency}/>}
  </div>;
}
