"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency = "usd" | "cny";
type Period = "7D" | "30D" | "90D";
type DetailKey = "price" | "supply" | "staking" | "unlock" | "buyback" | "volume" | null;
type MarketData = { price:number; change24h:number; marketCap:number; fdv:number; volume24h:number; circulatingSupply:number; totalSupply:number; high24h:number; low24h:number; ath:number; athDate:string; chart:Array<[number,number]>; source:string; stale:boolean; updatedAt:string };
type ChainRow = { name:string; shares:number; rate:number; staked:number; pending:number; ok:boolean };
type ChainData = { ethfiSupply:number; burned:number; staked:number; pending:number; chains:ChainRow[]; source:string; stale:boolean; updatedAt:string };

const fallbackMarket: MarketData = {
  price:0.4046, change24h:-1.1, marketCap:393_800_000, fdv:404_600_000, volume24h:69_400_000,
  circulatingSupply:973_468_000, totalSupply:1_000_000_000, high24h:0.423, low24h:0.397, ath:8.53,
  athDate:"2024-03-27T00:00:00.000Z", chart:Array.from({length:90},(_,i)=>[Date.now()-(89-i)*86_400_000,0.46-i*0.00055+Math.sin(i/5)*0.018]),
  source:"最近一次可用快照", stale:true, updatedAt:new Date().toISOString(),
};
const fallbackChain: ChainData = {
  ethfiSupply:1_000_000_000, burned:0, staked:91_700_000, pending:2_340_000,
  chains:[
    {name:"Ethereum",shares:84_900_000,rate:1.06,staked:90_000_000,pending:2_100_000,ok:false},
    {name:"Arbitrum",shares:1_430_000,rate:1.05,staked:1_500_000,pending:190_000,ok:false},
    {name:"Base",shares:190_000,rate:1.04,staked:200_000,pending:50_000,ok:false},
  ], source:"最近一次可用快照", stale:true, updatedAt:new Date().toISOString(),
};
const unlocks = [
  {date:"2026-09-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2026-10-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2026-11-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2026-12-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2027-01-15",amount:8_945_833,group:"核心贡献者与投资人"},{date:"2027-02-15",amount:8_945_833,group:"核心贡献者与投资人"},
  {date:"2027-03-15",amount:8_945_833,group:"核心贡献者与投资人"},
];
const allocation = [
  {label:"投资人",value:33.74,color:"#181b1a"},{label:"生态金库",value:21.62,color:"#2f6f5e"},{label:"核心贡献者",value:21.47,color:"#87ae9f"},
  {label:"用户空投",value:19.27,color:"#dfab57"},{label:"合作与流动性",value:3.9,color:"#e8e4db"},
];

const compact = (v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money = (v:number,c:Currency,d=2)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c.toUpperCase(),minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const fullNumber = (v:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:0}).format(v);
const daysUntil = (date:string)=>Math.max(0,Math.ceil((new Date(`${date}T00:00:00+08:00`).getTime()-Date.now())/86_400_000));
const formatTime = (value:string)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value));

function TrendChart({data,positive}:{data:Array<[number,number]>;positive:boolean}) {
  const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=canvasRef.current; if(!canvas||data.length<2)return;
    const render=()=>{
      const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1;
      canvas.width=Math.max(1,box.width*scale); canvas.height=Math.max(1,box.height*scale);
      const ctx=canvas.getContext("2d"); if(!ctx)return; ctx.scale(scale,scale);
      const w=box.width,h=box.height,p={top:20,right:10,bottom:22,left:10},values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;
      const color=positive?"#277a63":"#b45a43"; ctx.clearRect(0,0,w,h); ctx.strokeStyle="rgba(24,27,26,.08)"; ctx.lineWidth=1;
      for(let i=0;i<4;i++){const y=p.top+((h-p.top-p.bottom)/3)*i;ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}
      const pts=data.map((x,i)=>({x:p.left+(i/(data.length-1))*(w-p.left-p.right),y:p.top+((max-x[1])/range)*(h-p.top-p.bottom)}));
      const gradient=ctx.createLinearGradient(0,p.top,0,h);gradient.addColorStop(0,positive?"rgba(39,122,99,.22)":"rgba(180,90,67,.18)");gradient.addColorStop(1,"rgba(255,255,255,0)");
      ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.lineTo(pts.at(-1)!.x,h-p.bottom);ctx.lineTo(pts[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();
      ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.lineJoin="round";ctx.stroke();
      const last=pts.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();
    }; render(); const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect();
  },[data,positive]);
  return <canvas ref={canvasRef} className="trend-canvas" aria-label="ETHFI 价格趋势图"/>;
}

function MetricCard({eyebrow,value,meta,tone,onClick}:{eyebrow:string;value:string;meta:string;tone?:"positive"|"negative"|"warning";onClick:()=>void}){
  return <button className="metric-card" onClick={onClick} type="button"><span className="metric-topline"><span>{eyebrow}</span><span className="arrow">↗</span></span><strong>{value}</strong><span className={`metric-meta ${tone||""}`}>{meta}</span></button>;
}

function DetailDrawer({active,onClose,market,chain,currency}:{active:DetailKey;onClose:()=>void;market:MarketData;chain:ChainData;currency:Currency}){
  useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  if(!active)return null;
  const content:Record<Exclude<DetailKey,null>,{title:string;kicker:string;body:React.ReactNode}>={
    price:{title:"价格与估值",kicker:"Market overview",body:<><div className="drawer-hero"><span>ETHFI 现价</span><strong>{money(market.price,currency,4)}</strong><em className={market.change24h>=0?"positive":"negative"}>{market.change24h>=0?"+":""}{market.change24h.toFixed(2)}% · 24H</em></div><div className="detail-grid"><div><span>24H 最高</span><strong>{money(market.high24h,currency,4)}</strong></div><div><span>24H 最低</span><strong>{money(market.low24h,currency,4)}</strong></div><div><span>流通市值</span><strong>{money(market.marketCap,currency,0)}</strong></div><div><span>完全稀释估值</span><strong>{money(market.fdv,currency,0)}</strong></div><div><span>历史最高</span><strong>{money(market.ath,currency,2)}</strong></div><div><span>距历史高点</span><strong>{((market.price/market.ath-1)*100).toFixed(1)}%</strong></div></div><p className="drawer-note">行情由 CoinGecko 聚合，用于市场观察，不构成投资建议。</p></>},
    supply:{title:"供应与流通",kicker:"Supply intelligence",body:<><div className="drawer-hero"><span>当前流通率</span><strong>{(market.circulatingSupply/chain.ethfiSupply*100).toFixed(2)}%</strong><em>{compact(market.circulatingSupply)} / {compact(chain.ethfiSupply)} ETHFI</em></div><div className="supply-bar large"><i style={{width:`${Math.min(100,market.circulatingSupply/chain.ethfiSupply*100)}%`}}/></div><div className="detail-grid"><div><span>合约总供应</span><strong>{fullNumber(chain.ethfiSupply)}</strong></div><div><span>市场流通量</span><strong>{fullNumber(market.circulatingSupply)}</strong></div><div><span>未流通</span><strong>{fullNumber(Math.max(0,chain.ethfiSupply-market.circulatingSupply))}</strong></div><div><span>链上累计销毁</span><strong>{fullNumber(chain.burned)}</strong></div></div><p className="drawer-note">ETHFI 已固定铸造 10 亿枚。“未流通”不等同于“未解锁”，流通口径以市场数据商认定为准。</p></>},
    staking:{title:"ETHFI 质押",kicker:"sETHFI across chains",body:<><div className="drawer-hero"><span>估算质押资产</span><strong>{compact(chain.staked)} ETHFI</strong><em>{(chain.staked/market.circulatingSupply*100).toFixed(2)}% 流通量</em></div><div className="chain-list">{chain.chains.map(item=><div className="chain-row" key={item.name}><span className="chain-name"><i className={item.ok?"live-dot":"fallback-dot"}/>{item.name}</span><span>{compact(item.staked)} 质押</span><span>{compact(item.pending)} 解押中</span></div>)}</div><p className="drawer-note">质押资产按 sETHFI 份额供应量 × Accountant 链上汇率计算；解押通常进入最长约 10 天的队列。</p></>},
    unlock:{title:"未来解锁",kicker:"Unlock calendar",body:<><div className="drawer-hero"><span>剩余排期</span><strong>{compact(unlocks.reduce((s,x)=>s+x.amount,0))} ETHFI</strong><em>预计至 2027 年 3 月</em></div><div className="unlock-list full">{unlocks.map((item,index)=><div className="unlock-row" key={item.date}><span className="unlock-index">{String(index+1).padStart(2,"0")}</span><div><strong>{new Date(`${item.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"})}</strong><small>{item.group}</small></div><div className="unlock-amount"><strong>{compact(item.amount)}</strong><small>{(item.amount/market.totalSupply*100).toFixed(2)}% 总供应</small></div></div>)}</div><p className="drawer-note">解锁日历为公开代币经济排期；实际进入交易流通仍取决于接收钱包后续动作。</p></>},
    buyback:{title:"回购与销毁",kicker:"Protocol value flow",body:<><div className="drawer-hero"><span>链上确认销毁</span><strong>{compact(chain.burned)} ETHFI</strong><em>总供应减少口径</em></div><div className="flow-stack"><div><b>01</b><span><strong>协议收入</strong><small>提现费与部分协议收入</small></span></div><div><b>02</b><span><strong>市场回购</strong><small>周度与月度执行</small></span></div><div><b>03</b><span><strong>分配给 sETHFI</strong><small>增加质押参与者价值</small></span></div></div><div className="notice"><strong>回购 ≠ 销毁</strong><p>官方机制主要将回购所得分配给 sETHFI 持有人。只有总供应实际减少或代币进入不可恢复地址，才计入销毁。</p></div></>},
    volume:{title:"交易与流动性",kicker:"Market activity",body:<><div className="drawer-hero"><span>24H 市场成交额</span><strong>{money(market.volume24h,currency,0)}</strong><em>成交额 / 市值 {(market.volume24h/market.marketCap*100).toFixed(1)}%</em></div><div className="detail-grid"><div><span>流通市值</span><strong>{money(market.marketCap,currency,0)}</strong></div><div><span>FDV</span><strong>{money(market.fdv,currency,0)}</strong></div><div><span>流通率</span><strong>{(market.circulatingSupply/market.totalSupply*100).toFixed(1)}%</strong></div><div><span>24H 振幅</span><strong>{((market.high24h-market.low24h)/market.low24h*100).toFixed(1)}%</strong></div></div><p className="drawer-note">这里展示的是聚合市场成交额；DEX 成交和链上 Transfer 流量会作为后续独立口径接入。</p></>},
  };
  const current=content[active];
  return <div className="drawer-layer" role="dialog" aria-modal="true" aria-label={current.title}><button className="drawer-backdrop" onClick={onClose} aria-label="关闭详情"/><aside className="detail-drawer"><div className="drawer-head"><div><span>{current.kicker}</span><h2>{current.title}</h2></div><button type="button" onClick={onClose} aria-label="关闭">×</button></div><div className="drawer-body">{current.body}</div><div className="drawer-source"><span className={market.stale||chain.stale?"fallback-dot":"live-dot"}/> 数据更新于 {formatTime(active==="price"||active==="volume"?market.updatedAt:chain.updatedAt)}</div></aside></div>;
}

export default function Home(){
  const [market,setMarket]=useState<MarketData>(fallbackMarket),[chain,setChain]=useState<ChainData>(fallbackChain),[currency,setCurrency]=useState<Currency>("usd"),[period,setPeriod]=useState<Period>("30D"),[detail,setDetail]=useState<DetailKey>(null),[refreshing,setRefreshing]=useState(false),[mobileNav,setMobileNav]=useState(false);
  const loadData=useCallback(async(force=false)=>{setRefreshing(true);const suffix=force?`&refresh=${Date.now()}`:"";try{const [m,c]=await Promise.allSettled([fetch(`/api/market?currency=${currency}${suffix}`).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`/api/chain?${force?`refresh=${Date.now()}`:"source=auto"}`).then(r=>{if(!r.ok)throw new Error();return r.json()})]);if(m.status==="fulfilled")setMarket(m.value);if(c.status==="fulfilled")setChain(c.value)}finally{setRefreshing(false)}},[currency]);
  useEffect(()=>{loadData();const timer=window.setInterval(()=>loadData(),60_000);return()=>window.clearInterval(timer)},[loadData]);
  const filteredChart=useMemo(()=>{const wanted=period==="7D"?7:period==="30D"?30:90,threshold=Date.now()-wanted*86_400_000,selected=market.chart.filter(x=>x[0]>=threshold);return selected.length>1?selected:market.chart.slice(-wanted)},[market.chart,period]);
  const nextUnlock=unlocks.find(x=>new Date(`${x.date}T23:59:59+08:00`).getTime()>Date.now())||unlocks.at(-1)!;
  const nonCirculating=Math.max(0,chain.ethfiSupply-market.circulatingSupply),circulatingPct=Math.min(100,market.circulatingSupply/chain.ethfiSupply*100),chartPositive=filteredChart.length>1&&filteredChart.at(-1)![1]>=filteredChart[0][1];
  const donut=`conic-gradient(${allocation.map((item,index)=>{const start=allocation.slice(0,index).reduce((s,x)=>s+x.value,0);return `${item.color} ${start}% ${start+item.value}%`}).join(",")})`;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?"open":""}`}><a className="brand" href="#overview" aria-label="ETHFI Lens 首页"><span className="brand-mark">e</span><span>ETHFI<span>lens</span></span></a><nav aria-label="主导航"><a className="active" href="#overview" onClick={()=>setMobileNav(false)}><i>01</i>总览</a><a href="#market" onClick={()=>setMobileNav(false)}><i>02</i>市场</a><a href="#supply" onClick={()=>setMobileNav(false)}><i>03</i>供应</a><a href="#staking" onClick={()=>setMobileNav(false)}><i>04</i>质押</a><a href="#unlocks" onClick={()=>setMobileNav(false)}><i>05</i>解锁</a></nav><div className="sidebar-foot"><span className={market.stale||chain.stale?"fallback-dot":"live-dot"}/><div><strong>{market.stale||chain.stale?"部分使用快照":"数据源正常"}</strong><small>每 60 秒自动同步</small></div></div></aside>
    <main><header className="topbar"><button className="menu-button" type="button" onClick={()=>setMobileNav(v=>!v)} aria-label="打开导航">☰</button><div className="breadcrumb"><span>ETHFI</span><b>/</b><strong>数据总览</strong></div><div className="top-actions"><div className="currency-switch" aria-label="计价币种"><button type="button" className={currency==="usd"?"active":""} onClick={()=>setCurrency("usd")}>USD</button><button type="button" className={currency==="cny"?"active":""} onClick={()=>setCurrency("cny")}>CNY</button></div><span className="updated">更新 {formatTime(market.updatedAt)}</span><button className={`refresh-button ${refreshing?"loading":""}`} type="button" onClick={()=>loadData(true)} disabled={refreshing}><span>↻</span>{refreshing?"刷新中":"刷新数据"}</button></div></header>
      <div className="content">
        <section className="hero" id="overview"><div><span className="section-kicker">ETHER.FI TOKEN INTELLIGENCE</span><h1>看懂 ETHFI，<br/><em>不只看价格。</em></h1><p>市场、供应、质押与解锁信号，汇总在一个干净的视图里。</p></div><div className="hero-token"><div className="token-orbit"><span>ETHFI</span></div><div><small>官方合约</small><strong>0xfe0c...cc0eb</strong><a href="https://etherscan.io/token/0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb" target="_blank" rel="noreferrer">在 Etherscan 验证 ↗</a></div></div></section>
        <section className="metrics-grid" aria-label="关键指标"><MetricCard eyebrow="当前价格" value={money(market.price,currency,4)} meta={`${market.change24h>=0?"+":""}${market.change24h.toFixed(2)}% · 24H`} tone={market.change24h>=0?"positive":"negative"} onClick={()=>setDetail("price")}/><MetricCard eyebrow="流通市值" value={money(market.marketCap,currency,0)} meta={`FDV ${money(market.fdv,currency,0)}`} onClick={()=>setDetail("price")}/><MetricCard eyebrow="24H 交易量" value={money(market.volume24h,currency,0)} meta={`${(market.volume24h/market.marketCap*100).toFixed(1)}% 换手/市值`} onClick={()=>setDetail("volume")}/><MetricCard eyebrow="流通供应" value={`${compact(market.circulatingSupply)} ETHFI`} meta={`${circulatingPct.toFixed(2)}% 总供应`} tone="positive" onClick={()=>setDetail("supply")}/><MetricCard eyebrow="质押资产" value={`${compact(chain.staked)} ETHFI`} meta={`${(chain.staked/market.circulatingSupply*100).toFixed(2)}% 流通量`} onClick={()=>setDetail("staking")}/><MetricCard eyebrow="下次解锁" value={`${daysUntil(nextUnlock.date)} 天`} meta={`${compact(nextUnlock.amount)} ETHFI`} tone="warning" onClick={()=>setDetail("unlock")}/></section>
        <section className="dashboard-grid" id="market"><article className="panel price-panel"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(x=><button type="button" className={period===x?"active":""} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div></div><div className="price-summary"><strong>{money(market.price,currency,4)}</strong><span className={chartPositive?"positive":"negative"}>{chartPositive?"↑":"↓"} {Math.abs((filteredChart.at(-1)?.[1]/filteredChart[0]?.[1]-1)*100||0).toFixed(2)}%</span></div><TrendChart data={filteredChart} positive={chartPositive}/><div className="chart-foot"><span>{new Date(filteredChart[0]?.[0]||Date.now()).toLocaleDateString("zh-CN",{month:"short",day:"numeric"})}</span><span>数据源 · {market.source}</span><span>现在</span></div></article>
          <article className="panel supply-panel" id="supply"><div className="panel-head"><div><span className="section-kicker">TOKEN SUPPLY</span><h2>供应状态</h2></div><button className="text-button" type="button" onClick={()=>setDetail("supply")}>查看详情 ↗</button></div><div className="supply-main"><div><span>已流通</span><strong>{circulatingPct.toFixed(2)}%</strong></div><div className="supply-ring" style={{"--progress":`${circulatingPct*3.6}deg`} as React.CSSProperties}><span>{compact(market.circulatingSupply)}</span><small>ETHFI</small></div></div><div className="supply-bar"><i style={{width:`${circulatingPct}%`}}/></div><div className="supply-legend"><div><i className="circulating"/><span>流通</span><strong>{compact(market.circulatingSupply)}</strong></div><div><i className="locked"/><span>未流通</span><strong>{compact(nonCirculating)}</strong></div><div><i className="burned"/><span>已销毁</span><strong>{compact(chain.burned)}</strong></div></div><p className="micro-note">固定供应 10 亿枚 · 未流通不等于未解锁</p></article></section>
        <section className="dashboard-grid lower-grid"><article className="panel staking-panel" id="staking"><div className="panel-head"><div><span className="section-kicker">STAKING FLOW</span><h2>质押与解押</h2></div><button className="text-button" type="button" onClick={()=>setDetail("staking")}>跨链明细 ↗</button></div><div className="staking-totals"><div><span>质押资产</span><strong>{compact(chain.staked)}</strong><small>ETHFI</small></div><div><span>解押中</span><strong>{compact(chain.pending)}</strong><small>ETHFI</small></div></div><div className="ratio-track"><i style={{width:`${Math.min(100,chain.pending/Math.max(1,chain.staked)*100*5)}%`}}/></div><div className="chain-chips">{chain.chains.map(x=><span key={x.name}><i className={x.ok?"live-dot":"fallback-dot"}/>{x.name}<b>{compact(x.staked)}</b></span>)}</div><div className="insight"><span>队列观察</span><p>当前解押量约占质押资产的 <strong>{(chain.pending/Math.max(1,chain.staked)*100).toFixed(2)}%</strong>，通常最长约 10 天完成。</p></div></article>
          <article className="panel unlock-panel" id="unlocks"><div className="panel-head"><div><span className="section-kicker">UNLOCK WATCH</span><h2>解锁雷达</h2></div><button className="text-button" type="button" onClick={()=>setDetail("unlock")}>完整日历 ↗</button></div><div className="unlock-callout"><div><span>下一事件</span><strong>{new Date(`${nextUnlock.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{month:"long",day:"numeric"})}</strong><small>{nextUnlock.group}</small></div><div><strong>{compact(nextUnlock.amount)}</strong><small>ETHFI · {(nextUnlock.amount/market.totalSupply*100).toFixed(2)}%</small></div></div><div className="timeline"><i/><span className="today" style={{left:"12%"}}><b>今天</b></span>{unlocks.slice(0,4).map((x,i)=><span className="event" style={{left:`${28+i*21}%`}} key={x.date}><b>{new Date(`${x.date}T00:00:00+08:00`).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"})}</b></span>)}</div><div className="unlock-risk"><span className="warning-dot"/><p>未来 30 天预计释放 <strong>{compact(nextUnlock.amount)} ETHFI</strong>，约为流通量的 {(nextUnlock.amount/market.circulatingSupply*100).toFixed(2)}%。</p></div></article>
          <article className="panel allocation-panel"><div className="panel-head"><div><span className="section-kicker">ALLOCATION</span><h2>代币分配</h2></div></div><div className="allocation-content"><div className="donut" style={{background:donut}}><span><strong>1B</strong><small>总供应</small></span></div><div className="allocation-list">{allocation.map(x=><div key={x.label}><i style={{background:x.color}}/><span>{x.label}</span><strong>{x.value}%</strong></div>)}</div></div></article></section>
        <section className="activity-strip"><div><span className="section-kicker">PROTOCOL ACTIONS</span><h2>回购、分配与销毁，要分开看。</h2></div><div className="action-cards"><button type="button" onClick={()=>setDetail("buyback")}><span>回购机制</span><strong>周度 + 月度</strong><small>协议收入驱动 ↗</small></button><button type="button" onClick={()=>setDetail("buyback")}><span>主要去向</span><strong>sETHFI 持有人</strong><small>价值再分配 ↗</small></button><button type="button" onClick={()=>setDetail("buyback")}><span>链上销毁</span><strong>{compact(chain.burned)} ETHFI</strong><small>总供应减少口径 ↗</small></button></div></section>
        <footer><div><span className="brand-mark small">e</span><strong>ETHFI lens</strong></div><p>数据用于研究与观察，不构成投资建议。</p><div><a href="https://etherfi.gitbook.io/gov/ethfi-allocations" target="_blank" rel="noreferrer">官方代币经济 ↗</a><a href="https://etherfi.gitbook.io/etherfi/ethfi/ethfi-staking" target="_blank" rel="noreferrer">质押文档 ↗</a></div></footer>
      </div></main>
    {mobileNav&&<button className="nav-backdrop" type="button" onClick={()=>setMobileNav(false)} aria-label="关闭导航"/>}<DetailDrawer active={detail} onClose={()=>setDetail(null)} market={market} chain={chain} currency={currency}/>
  </div>;
}
