"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Currency="usd";
type Period="7D"|"30D"|"90D";
type Epoch={timestamp:number;revenue:number;fees:number;buyback:number;airdrops:number};
type Overview={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;totalSupply:number;ath:number;high24h:number;low24h:number;chart:Array<[number,number]>;chartSource:string;venues:Array<{name:string;price:number;change24h:number;volume24h:number}>;spendle:{totalPendleStaked:number;directSpendle:number;virtualSpendle:number;allTimeRevenue:number;epochs:Epoch[];latestEpoch:Epoch|null;latestBuyback:(Epoch&{buyback:number})|null;withdrawalDays:number;instantExitFee:number}|null;terminalInflationRate:number;vestingStatus:string;currencyRate:number;marketSource:string;supplySource:string;sPendleSource:string;failedSources:string[];stale:boolean;updatedAt:string};
type Protocol={totalTvl:number;tradingVolume:number;activeMarkets:number;chains:Array<{chainId:number;name:string;tvl:number;markets:number}>;expiryWindows:Array<{days:number;markets:number;tvl:number}>;topMarkets:Array<{name:string;protocol:string;chain:string;chainId:number;address:string;expiry:string;tvl:number;volume:number;fixedApy:number;underlyingApy:number;lpApy:number;ytApy:number;pendleApy:number;isPrime:boolean}>;source:string;stale?:boolean;updatedAt:string};

const compact=(value:number,digits=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:digits}).format(value);
const money=(value:number,currency:Currency,digits=2)=>{void currency;return new Intl.NumberFormat("zh-CN",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)};
const percent=(value:number)=>`${(value*100).toFixed(2)}%`;
const time=(value:string)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value));
const date=(value:number|string)=>new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric"}).format(new Date(value));
const daysTo=(value:string,now:number)=>Math.max(0,Math.ceil((new Date(value).getTime()-now)/86_400_000));

function PendleChart({data,label}:{data:Array<[number,number]>;label:string}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas||data.length<2)return;const render=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p={top:18,right:12,bottom:18,left:12};canvas.width=Math.max(1,w*scale);canvas.height=Math.max(1,h*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);const values=data.map(item=>item[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1,pts=data.map((item,index)=>({x:p.left+index/(data.length-1)*(w-p.left-p.right),y:p.top+(max-item[1])/range*(h-p.top-p.bottom)}));ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(20,48,54,.09)";ctx.lineWidth=1;for(let i=0;i<4;i++){const y=p.top+i/3*(h-p.top-p.bottom);ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(w-p.right,y);ctx.stroke()}const gradient=ctx.createLinearGradient(0,p.top,0,h);gradient.addColorStop(0,"rgba(27,190,166,.24)");gradient.addColorStop(1,"rgba(27,190,166,0)");ctx.beginPath();pts.forEach((pt,index)=>index?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.lineTo(pts.at(-1)!.x,h-p.bottom);ctx.lineTo(pts[0].x,h-p.bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();pts.forEach((pt,index)=>index?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.strokeStyle="#19aF9d";ctx.lineWidth=2.6;ctx.lineJoin="round";ctx.stroke();const last=pts.at(-1)!;ctx.beginPath();ctx.arc(last.x,last.y,4,0,Math.PI*2);ctx.fillStyle="#117d72";ctx.fill()};render();const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect()},[data]);
  return <canvas ref={ref} className="pendle-chart" aria-label={label}/>;
}

function PendleMetric({label,value,meta,tone}:{label:string;value:string;meta:string;tone?:"positive"|"negative"|"warning"}){return <article className="metric-card pendle-metric"><span className="metric-topline"><span>{label}</span><span className="arrow">↗</span></span><strong>{value}</strong><span className={`metric-meta ${tone||""}`}>{meta}</span></article>}

export default function PendleDashboard({currency,refreshNonce=0}:{currency:Currency;refreshNonce?:number}){
  const [overview,setOverview]=useState<Overview|null>(null),[protocol,setProtocol]=useState<Protocol|null>(null),[error,setError]=useState<string|null>(null),[period,setPeriod]=useState<Period>("30D");
  const load=useCallback(async()=>{setError(null);const stamp=Date.now();const [overviewResult,protocolResult]=await Promise.allSettled([fetch(`/api/pendle?currency=${currency}&t=${stamp}`).then(async response=>{if(!response.ok)throw new Error("PENDLE 行情与 sPENDLE 数据暂时不可用");return response.json()}),fetch(`/api/pendle-markets?t=${stamp}`).then(async response=>{if(!response.ok)throw new Error("Pendle 活跃市场暂时不可用");return response.json()})]);if(overviewResult.status==="fulfilled")setOverview(overviewResult.value);else{setOverview(null);setError(overviewResult.reason instanceof Error?overviewResult.reason.message:"PENDLE 数据暂时不可用")}if(protocolResult.status==="fulfilled")setProtocol(protocolResult.value);else setProtocol(null)},[currency]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,30_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const chart=useMemo(()=>{if(!overview)return[];const days=period==="7D"?7:period==="30D"?30:90,threshold=new Date(overview.updatedAt).getTime()-days*86_400_000,rows=overview.chart.filter(item=>item[0]>=threshold);return rows.length>1?rows:overview.chart.slice(-days)},[overview,period]);
  if(!overview)return <section className="bp-loading pendle-loading" aria-live="polite"><div><span className={error?"fallback-dot":"live-dot"}/><strong>{error||"正在连接 PENDLE 行情与 Pendle 协议数据"}</strong><small>{error?"不会使用旧数字冒充实时结果":"行情、sPENDLE、收入与活跃市场同时载入"}</small>{error?<button type="button" onClick={load}>重新获取</button>:null}</div><div className="loading-metrics">{Array.from({length:6},(_,index)=><i key={index}/>)}</div><div className="loading-panels"><i/><i/><i/></div></section>;
  const now=new Date(overview.updatedAt).getTime(),priceStart=chart[0]?.[1]??overview.price,periodChange=priceStart>0?(overview.price/priceStart-1)*100:0,stakeRatio=overview.totalSupply>0?(overview.spendle?.totalPendleStaked??0)/overview.totalSupply*100:0,rate=overview.currencyRate||1,latestEpoch=overview.spendle?.latestEpoch,latestBuyback=overview.spendle?.latestBuyback,topChain=protocol?.chains[0],expiry30=protocol?.expiryWindows.find(item=>item.days===30),marketTone=overview.change24h>=0&&periodChange>=0?"tone-positive":overview.change24h<0&&periodChange<0?"tone-negative":"tone-neutral";
  const signals=[
    {label:"市场",title:marketTone==="tone-positive"?"短中期价格动能偏强":marketTone==="tone-negative"?"短中期价格承压":"短中期方向分化",detail:`24H ${overview.change24h>=0?"+":""}${overview.change24h.toFixed(2)}% · ${period} ${periodChange>=0?"+":""}${periodChange.toFixed(2)}%`,tone:marketTone},
    {label:"协议使用",title:protocol?`${protocol.activeMarkets} 个活跃收益市场`:"活跃市场数据暂不可读",detail:protocol?`活跃市场 TVL ${money(protocol.totalTvl*rate,currency,0)} · ${protocol.chains.length} 条链`:"只隐藏协议模块，行情与 sPENDLE 保持显示",tone:protocol?"tone-positive":"tone-neutral"},
    {label:"sPENDLE",title:overview.spendle?`${compact(overview.spendle.totalPendleStaked)} PENDLE 已质押`:"sPENDLE 数据暂不可读",detail:overview.spendle?`约占总供应 ${stakeRatio.toFixed(2)}% · 普通退出等待 ${overview.spendle.withdrawalDays} 天`:"不使用 vePENDLE 旧接口补值",tone:overview.spendle?"tone-positive":"tone-neutral"},
    {label:"排放 / 回购",title:"已进入终端激励通胀阶段",detail:`年化目标 ${overview.terminalInflationRate}% · ${latestBuyback?`最近可验证回购 ${money(latestBuyback.buyback,currency,0)}`:"回购周期值暂不可读"}`,tone:"tone-warning"}
  ];
  const maxEpoch=Math.max(1,...(overview.spendle?.epochs??[]).slice(-8).map(item=>Math.max(item.revenue,item.buyback)));
  return <div className="pendle-dashboard">
    <section className="metrics-grid" aria-label="PENDLE 关键指标"><PendleMetric label="PENDLE 当前价格" value={money(overview.price,currency,4)} meta={`${overview.change24h>=0?"+":""}${overview.change24h.toFixed(2)}% · ${overview.marketSource}`} tone={overview.change24h>=0?"positive":"negative"}/><PendleMetric label="流通市值" value={money(overview.marketCap,currency,0)} meta={`FDV ${money(overview.fdv,currency,0)}`}/><PendleMetric label="24H 三所现货量" value={money(overview.volume24h,currency,0)} meta={overview.marketCap>0?`${(overview.volume24h/overview.marketCap*100).toFixed(1)}% 成交额/市值`:"市场口径"}/><PendleMetric label="活跃市场 TVL" value={protocol?money(protocol.totalTvl*rate,currency,0):"暂不可读"} meta={protocol?`${protocol.activeMarkets} 市场 · ${protocol.chains.length} 链`:"Pendle Core API"}/><PendleMetric label="PENDLE 已质押" value={overview.spendle?`${compact(overview.spendle.totalPendleStaked)} PENDLE`:"暂不可读"} meta={overview.spendle?`${stakeRatio.toFixed(2)}% 总供应 · sPENDLE`:`${overview.sPendleSource}`}/><PendleMetric label="最近可验证回购" value={latestBuyback?money(latestBuyback.buyback,currency,0):"暂不可读"} meta={latestBuyback?`${date(latestBuyback.timestamp)} 周期记录`:"不把缺失值当作 0"} tone="warning"/></section>
    <nav className="bp-section-nav pendle-section-nav" aria-label="PENDLE 页面导航"><a href="#pendle-overview">总览</a><a href="#pendle-market">市场</a><a href="#pendle-spendle">sPENDLE</a><a href="#pendle-yields">收益市场</a><a href="#pendle-supply">供应排放</a></nav>
    <section className="signal-board pendle-signal-board" id="pendle-overview"><div className="signal-board-head"><div><span className="section-kicker">PENDLE AUTOMATED BRIEF</span><h1>{overview.spendle&&protocol?"代币价值捕获与协议使用，需要放在一起看。":"部分协议源暂不可用，保留可验证模块。"}</h1></div><p>基于三所行情、Pendle 活跃收益市场、sPENDLE 质押和官方收入回购周期自动生成。</p><em><i className={overview.stale||protocol?.stale?"fallback-dot":"live-dot"}/>{overview.stale||!protocol?"部分源异常":"实时规则引擎"} · {time(overview.updatedAt)}</em></div><div className="signal-grid">{signals.map(item=><article className={`signal-card ${item.tone}`} key={item.label}><span>{item.label}</span><strong>{item.title}</strong><p>{item.detail}</p></article>)}</div></section>
    <section className="dashboard-grid pendle-top-grid" id="pendle-market"><article className="panel pendle-price-panel"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D"] as Period[]).map(value=><button type="button" className={period===value?"active":""} onClick={()=>setPeriod(value)} key={value}>{value}</button>)}</div></div><div className="price-summary"><strong>{money(overview.price,currency,4)}</strong><span className={periodChange>=0?"positive":"negative"}>{periodChange>=0?"↑":"↓"} {Math.abs(periodChange).toFixed(2)}%</span></div>{chart.length>1?<PendleChart data={chart} label="PENDLE 价格趋势图"/>:<div className="bp-chart-empty"><span className="fallback-dot"/>交易所 K 线暂不可读</div>}<div className="chart-foot"><span>{chart[0]?date(chart[0][0]):"—"}</span><span>K 线 · {overview.chartSource}　报价 · {overview.marketSource}</span><span>现在</span></div></article>
      <article className="panel pendle-protocol-panel"><div className="panel-head"><div><span className="section-kicker">PROTOCOL FOOTPRINT</span><h2>活跃市场分布</h2></div><a className="text-button" href="https://app.pendle.finance/trade/markets" target="_blank" rel="noreferrer">官方市场 ↗</a></div>{protocol?<><div className="pendle-protocol-hero"><div><span>未到期市场 TVL 合计</span><strong>{money(protocol.totalTvl*rate,currency,0)}</strong><small>{protocol.activeMarkets} 个市场</small></div><div><span>市场成交量快照</span><strong>{money(protocol.tradingVolume*rate,currency,0)}</strong><small>{protocol.chains.length} 条链</small></div></div><div className="pendle-chain-list">{protocol.chains.slice(0,5).map(chain=><div key={chain.chainId}><span><b>{chain.name}</b><small>{chain.markets} 市场</small></span><i><b style={{width:`${topChain&&topChain.tvl>0?Math.max(3,chain.tvl/topChain.tvl*100):0}%`}}/></i><strong>{compact(chain.tvl*rate)}</strong></div>)}</div><p className="micro-note">{protocol.source} · {time(protocol.updatedAt)}</p></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>活跃市场暂不可读</strong><p>行情与 sPENDLE 数据仍保持实时显示。</p></div>}</article></section>
    <section className="dashboard-grid pendle-middle-grid"><article className="panel pendle-spendle-panel" id="pendle-spendle"><div className="panel-head"><div><span className="section-kicker">STAKING & VALUE CAPTURE</span><h2>sPENDLE 与协议收入</h2></div><a className="text-button" href="https://app.pendle.finance/governance" target="_blank" rel="noreferrer">官方质押页 ↗</a></div>{overview.spendle?<><div className="pendle-stake-grid"><div><span>实际质押 PENDLE</span><strong>{compact(overview.spendle.totalPendleStaked)}</strong><small>{stakeRatio.toFixed(2)}% 总供应</small></div><div><span>直接 sPENDLE</span><strong>{compact(overview.spendle.directSpendle)}</strong><small>当前质押合约</small></div><div><span>遗留虚拟 sPENDLE</span><strong>{compact(overview.spendle.virtualSpendle)}</strong><small>vePENDLE 迁移余额</small></div></div><div className="pendle-exit-note"><span className="warning-dot"/><p><strong>普通退出等待 {overview.spendle.withdrawalDays} 天；立即退出费用 {overview.spendle.instantExitFee}% 。</strong>虚拟 sPENDLE 仅反映遗留 vePENDLE 治理余额，不与直接质押量相加作为资产 TVL。</p></div><div className="pendle-revenue-head"><span>最近 8 个官方周期</span><strong>累计收入 {money(overview.spendle.allTimeRevenue,currency,0)}</strong></div><div className="pendle-revenue-chart" aria-label="sPENDLE 收入与回购周期图">{overview.spendle.epochs.slice(-8).map(epoch=><div key={epoch.timestamp}><span><i className="revenue" style={{height:`${Math.max(2,epoch.revenue/maxEpoch*100)}%`}}/><i className="buyback" style={{height:`${Math.max(0,epoch.buyback/maxEpoch*100)}%`}}/></span><small>{date(epoch.timestamp)}</small></div>)}</div><div className="pendle-chart-legend"><span><i className="revenue"/>协议收入</span><span><i className="buyback"/>回购</span><em>{latestEpoch?`最近周期收入 ${money(latestEpoch.revenue,currency,0)}`:"周期数据暂不可读"}</em></div></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>sPENDLE 数据暂不可读</strong><p>不会用已废弃的 vePENDLE 接口补值。</p></div>}</article>
      <article className="panel pendle-maturity-panel"><div className="panel-head"><div><span className="section-kicker">MATURITY RADAR</span><h2>到期集中度</h2></div></div>{protocol?<><div className="pendle-expiry-list">{protocol.expiryWindows.map(window=><div key={window.days}><span><strong>{window.days} 天内</strong><small>{window.markets} 个市场</small></span><b>{money(window.tvl*rate,currency,0)}</b><em>{protocol.totalTvl>0?`${(window.tvl/protocol.totalTvl*100).toFixed(1)}% TVL`:"—"}</em></div>)}</div><div className="pendle-risk-callout"><span className={expiry30&&expiry30.tvl/protocol.totalTvl>.35?"warning-dot":"live-dot"}/><p>{expiry30&&expiry30.tvl/protocol.totalTvl>.35?"未来 30 天到期 TVL 占比较高，需关注资金滚动和新市场承接。":"未来 30 天到期 TVL 未形成过度集中。"}</p></div></>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>到期分布暂不可读</strong></div>}</article>
      <article className="panel pendle-supply-panel" id="pendle-supply"><div className="panel-head"><div><span className="section-kicker">SUPPLY & EMISSIONS</span><h2>供应与持续排放</h2></div></div><div className="pendle-supply-hero"><strong>{overview.totalSupply>0?(overview.circulatingSupply/overview.totalSupply*100).toFixed(1):"—"}%</strong><span>市场流通口径</span></div><div className="bp-supply-bar"><i style={{width:`${overview.totalSupply>0?Math.min(100,overview.circulatingSupply/overview.totalSupply*100):0}%`}}/></div><div className="pendle-supply-list"><div><span>流通供应</span><strong>{compact(overview.circulatingSupply)} PENDLE</strong></div><div><span>总供应</span><strong>{compact(overview.totalSupply)} PENDLE</strong></div><div><span>终端激励通胀</span><strong>约 {overview.terminalInflationRate}% / 年</strong></div><div><span>团队与投资人归属</span><strong>已完成</strong></div></div><p className="micro-note">供应来源：{overview.supplySource}。不展示已经结束的团队/投资人解锁倒计时；新增供应主要观察激励排放与治理调整。</p></article></section>
    <section className="panel pendle-market-radar" id="pendle-yields"><div className="panel-head"><div><span className="section-kicker">YIELD MARKET RADAR</span><h2>头部活跃收益市场</h2></div><span className="pendle-market-count">按 TVL 排序 · {protocol?.topMarkets.length??0} 个</span></div>{protocol?<div className="pendle-table-wrap"><div className="pendle-market-table"><div className="pendle-market-row head"><span>市场 / 协议</span><span>网络</span><span>到期</span><span>固定 APY</span><span>底层 APY</span><span>LP APY</span><span>TVL</span></div>{protocol.topMarkets.map(market=><a className="pendle-market-row" href={`https://app.pendle.finance/trade/markets/${market.chainId}/${market.address}/swap?view=pt`} target="_blank" rel="noreferrer" key={`${market.chainId}-${market.address}`}><span><strong>{market.name}{market.isPrime?<i>PRIME</i>:null}</strong><small>{market.protocol}</small></span><span>{market.chain}</span><span>{daysTo(market.expiry,now)} 天</span><span className="positive">{percent(market.fixedApy)}</span><span>{percent(market.underlyingApy)}</span><span>{percent(market.lpApy)}</span><span>{money(market.tvl*rate,currency,0)}</span></a>)}</div></div>:<div className="bp-unavailable"><span className="fallback-dot"/><strong>收益市场排行暂不可读</strong><p>不会沿用过期市场或缓存排行。</p></div>}</section>
    <footer className="pendle-footer"><div><span className="brand-mark small">p</span><strong>PENDLE lens</strong></div><p>APY、TVL、收入和回购均可能变化；数据用于研究，不构成投资建议。</p><div><a href="https://www.pendle.finance/" target="_blank" rel="noreferrer">Pendle 官网 ↗</a><a href="https://docs.pendle.finance/pendle-v2/ProtocolMechanics/Mechanisms/sPENDLE" target="_blank" rel="noreferrer">sPENDLE 机制 ↗</a></div></footer>
  </div>;
}
