"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Token="hype"|"uni"|"bp";
type Props={refreshNonce?:number;onSelect:(token:Token)=>void};
type Hype={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;circulatingSupply:number;totalSupply:number;maxSupply:number;burnedSupply:number|null;chart:Array<[number,number]>;protocol:{perpsVolume24h:number;spotVolume24h:number|null;openInterest:number;perpMarkets:number}|null;staking:{totalStaked:number;stakingRatio:number;activeValidators:number;weightedApr:number;top5Share:number;withdrawalDays:number}|null;assistanceFund:{hype:number;bought30d:number|null;bought90d:number|null}|null;failedSources:string[]};
type Uni={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;chart:Array<[number,number]>;supply:{circulating:number;total:number;maximum:number;burned:number|null;burn30d:number|null;burn90d:number|null};protocol:{tvl:number|null;volume24h:number;volume7d:number;volume30d:number;fees24h:number;fees7d:number;fees30d:number;topChains:Array<{name:string;tvl:number}>};valueFlow:{status:string;feeCoverage:string};failedSources:string[]};
type Bp={price:number;change24h:number;marketCap:number;fdv:number;allMarketVolume24h:number;venueVolume24h:number;circulatingSupply:number;economicMaxSupply:number;staked:number|null;stakedPercent:number|null;cooldownDays:number;chart:Array<[number,number]>;liquidity:{spreadBps:number|null;bidDepth1Pct:number;askDepth1Pct:number;available:boolean};tokenomics:{preIpo:{amount:number;percent:number;status:string};postIpo:{amount:number;percent:number;status:string}};failedSources:string[]};

const compact=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const pct=(v:number|null,d=1)=>v==null?"—":`${v.toFixed(d)}%`;
const change30=(chart:Array<[number,number]>,price:number)=>{const rows=chart.slice(-31),start=rows[0]?.[1];return start>0?(price/start-1)*100:null};

export default function TriOverview({refreshNonce=0,onSelect}:Props){
  const [hype,setHype]=useState<Hype|null>(null),[uni,setUni]=useState<Uni|null>(null),[bp,setBp]=useState<Bp|null>(null),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const stamp=Date.now(),results=await Promise.allSettled([fetch(`/api/hype?currency=usd&t=${stamp}`).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`/api/uni?t=${stamp}`).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`/api/bp?currency=usd&t=${stamp}`).then(r=>{if(!r.ok)throw new Error();return r.json()})]);setHype(results[0].status==="fulfilled"?results[0].value:null);setUni(results[1].status==="fulfilled"?results[1].value:null);setBp(results[2].status==="fulfilled"?results[2].value:null);setLoading(false)},[]);
  useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);
  const assets=useMemo(()=>[
    {id:"hype" as const,name:"HYPE",project:"Hyperliquid",color:"#35c98c",price:hype?.price??null,change24:hype?.change24h??null,change30:hype?change30(hype.chart,hype.price):null,marketCap:hype?.marketCap??null,fdv:hype?.fdv??null,volume:hype?.volume24h??null,business:hype?.protocol?.perpsVolume24h??null,businessLabel:"永续 24H 成交",circulation:hype?hype.circulatingSupply/hype.maxSupply*100:null,staking:hype?.staking?hype.staking.totalStaked/hype.maxSupply*100:null,nextSupply:"质押奖励持续排放",valueStatus:"援助基金自动买入并销毁",flow30:hype?.assistanceFund?.bought30d??null,flow90:hype?.assistanceFund?.bought90d??null,burned:hype?.assistanceFund?.hype??hype?.burnedSupply??null,unit:"HYPE",health:hype?Math.max(0,100-hype.failedSources.length*15):0},
    {id:"uni" as const,name:"UNI",project:"Uniswap",color:"#ff4d9d",price:uni?.price??null,change24:uni?.change24h??null,change30:uni?change30(uni.chart,uni.price):null,marketCap:uni?.marketCap??null,fdv:uni?.fdv??null,volume:uni?.volume24h??null,business:uni?.protocol.volume30d??null,businessLabel:"协议 30D 成交",circulation:uni?uni.supply.circulating/uni.supply.maximum*100:null,staking:null,nextSupply:"无固定解锁；观察净供应",valueStatus:"协议费用程序化销毁",flow30:uni?.supply.burn30d??null,flow90:uni?.supply.burn90d??null,burned:uni?.supply.burned??null,unit:"UNI",health:uni?Math.max(0,100-uni.failedSources.length*15):0},
    {id:"bp" as const,name:"BP",project:"Backpack",color:"#e5484d",price:bp?.price??null,change24:bp?.change24h??null,change30:bp?change30(bp.chart,bp.price):null,marketCap:bp?.marketCap??null,fdv:bp?.fdv??null,volume:bp?.allMarketVolume24h??null,business:bp?.venueVolume24h??null,businessLabel:"Backpack 24H 成交",circulation:bp?bp.circulatingSupply/bp.economicMaxSupply*100:null,staking:bp?.stakedPercent??null,nextSupply:"37.5% Pre-IPO 里程碑触发",valueStatus:"未披露固定回购销毁",flow30:null,flow90:null,burned:null,unit:"BP",health:bp?Math.max(0,100-bp.failedSources.length*15):0},
  ],[hype,uni,bp]);
  return <div className="tri-overview">
    <section className="tri-hero"><div><span className="section-kicker">THREE-ASSET RESEARCH TERMINAL</span><h1>业务增长、供应压力与价值回流，<em>只看关键三币。</em></h1><p>HYPE、UNI、BP 使用统一市场与供应口径；协议业务、回购销毁和质押机制分别核验。</p></div><aside><span className={loading?"fallback-dot":"live-dot"}/><strong>{loading?"正在同步三币数据":"三币数据已同步"}</strong><small>{assets.filter(x=>x.health>=85).length}/3 数据完整度达到 85%</small></aside></section>
    <section className="tri-asset-grid">{assets.map(asset=><button type="button" onClick={()=>onSelect(asset.id)} style={{"--asset":asset.color} as React.CSSProperties} key={asset.id}><header><i/><span><b>{asset.name}</b><small>{asset.project}</small></span><em>详情 →</em></header><strong>{asset.price==null?"—":`$${money(asset.price,4)}`}</strong><div><span className={(asset.change24??0)>=0?"positive":"negative"}>24H {asset.change24==null?"—":`${asset.change24>=0?"+":""}${asset.change24.toFixed(2)}%`}</span><span className={(asset.change30??0)>=0?"positive":"negative"}>30D {asset.change30==null?"—":`${asset.change30>=0?"+":""}${asset.change30.toFixed(1)}%`}</span></div><footer><span>流通市值 <b>{asset.marketCap==null?"—":`$${compact(asset.marketCap)}`}</b></span><span>FDV <b>{asset.fdv==null?"—":`$${compact(asset.fdv)}`}</b></span></footer></button>)}</section>
    <section className="panel tri-table-panel"><div className="panel-head"><div><span className="section-kicker">MARKET & BUSINESS</span><h2>市场与业务强度</h2></div><span className="compare-note">金额统一为 USD</span></div><div className="tri-table-wrap"><table className="tri-table"><thead><tr><th>资产</th><th>24H现货量</th><th>成交额/市值</th><th>核心业务指标</th><th>业务/FDV</th><th>数据状态</th></tr></thead><tbody>{assets.map(x=><tr key={x.id}><th><i style={{background:x.color}}/>{x.name}</th><td>{x.volume==null?"—":`$${compact(x.volume)}`}</td><td>{x.volume&&x.marketCap?pct(x.volume/x.marketCap*100):"—"}</td><td><strong>{x.businessLabel}</strong><small>{x.business==null?"暂不可读":`$${compact(x.business)}`}</small></td><td>{x.business&&x.fdv?pct(x.business/x.fdv*100,2):"—"}</td><td><span className={x.health>=85?"tri-status good":"tri-status warning"}>{x.health}%</span></td></tr>)}</tbody></table></div></section>
    <section className="panel tri-table-panel"><div className="panel-head"><div><span className="section-kicker">SUPPLY PRESSURE</span><h2>供应与抛压缓冲</h2></div><span className="compare-note">流通与质押均除以整体供应</span></div><div className="tri-table-wrap"><table className="tri-table"><thead><tr><th>资产</th><th>流通率</th><th>质押率</th><th>退出约束</th><th>下一供应压力</th><th>判断</th></tr></thead><tbody>{assets.map(x=><tr key={x.id}><th><i style={{background:x.color}}/>{x.name}</th><td>{pct(x.circulation)}</td><td>{x.id==="uni"?"不适用":pct(x.staking)}</td><td>{x.id==="hype"?"7天转回现货":x.id==="bp"?"7天冷却":"无原生质押"}</td><td><strong>{x.nextSupply}</strong></td><td><span className={`tri-status ${x.id==="bp"?"warning":x.id==="hype"?"neutral":"good"}`}>{x.id==="bp"?"条件供应":x.id==="hype"?"持续排放":"净通缩观察"}</span></td></tr>)}</tbody></table></div></section>
    <section className="panel tri-table-panel"><div className="panel-head"><div><span className="section-kicker">VALUE FLOW</span><h2>回购、销毁与永久移除</h2></div><span className="compare-note">回购不自动等于销毁</span></div><div className="tri-table-wrap"><table className="tri-table"><thead><tr><th>资产</th><th>机制状态</th><th>30D实际流量</th><th>90D实际流量</th><th>累计永久移除</th><th>价值回流效率</th></tr></thead><tbody>{assets.map(x=><tr key={x.id}><th><i style={{background:x.color}}/>{x.name}</th><td><strong>{x.valueStatus}</strong></td><td>{x.flow30==null?"官方未提供":`${compact(x.flow30)} ${x.unit}`}</td><td>{x.flow90==null?"官方未提供":`${compact(x.flow90)} ${x.unit}`}</td><td>{x.burned==null?"官方未单列":`${compact(x.burned)} ${x.unit}`}</td><td>{x.flow30&&x.marketCap?pct(x.flow30*(x.price??0)/x.marketCap*100,4):"—"}</td></tr>)}</tbody></table></div></section>
  </div>
}
