"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Period="7D"|"30D"|"90D"|"1Y";
type UniData={price:number;change24h:number;marketCap:number;fdv:number;volume24h:number;high24h:number|null;low24h:number|null;venues:Array<{name:string;price:number;change:number;volume:number}>;chart:Array<[number,number]>;chartSource:string;supply:{circulating:number;total:number;maximum:number;effectiveSupply:number;burned:number|null;burn30d:number|null;burn90d:number|null;block:number|null;source:string};protocol:{tvl:number|null;volume24h:number;volume7d:number;volume30d:number;volumeAllTime:number;fees24h:number;fees7d:number;fees30d:number;feesAllTime:number;changeVolume7d:number;changeFees7d:number;topChains:Array<{name:string;tvl:number}>;source:string};valueFlow:{status:string;feeCoverage:string;burnDestination:string;method:string};failedSources:string[];updatedAt:string};
const compact=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:d}).format(v);
const money=(v:number,d=2)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
function Chart({data}:{data:Array<[number,number]>}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas||data.length<2)return;const draw=()=>{const box=canvas.getBoundingClientRect(),scale=window.devicePixelRatio||1,w=box.width,h=box.height,p=16;canvas.width=w*scale;canvas.height=h*scale;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.scale(scale,scale);const values=data.map(x=>x[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(40,30,45,.08)";for(let i=0;i<4;i++){const y=p+i/3*(h-p*2);ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}ctx.beginPath();data.forEach((row,i)=>{const x=p+i/(data.length-1)*(w-p*2),y=p+(max-row[1])/range*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle="#ff4d9d";ctx.lineWidth=2.6;ctx.stroke()};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect()},[data]);return <canvas className="uni-chart" ref={ref} aria-label="UNI 价格趋势"/>}
export default function UniDashboard({refreshNonce=0}:{refreshNonce?:number}){const [data,setData]=useState<UniData|null>(null),[period,setPeriod]=useState<Period>("30D"),[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{try{const r=await fetch(`/api/uni?t=${Date.now()}`);if(!r.ok)throw new Error("UNI 数据暂时不可用");setData(await r.json());setError(null)}catch(e){setData(null);setError(e instanceof Error?e.message:"UNI 数据暂时不可用")}},[]);useEffect(()=>{const initial=window.setTimeout(load,0),timer=window.setInterval(load,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load,refreshNonce]);const chart=useMemo(()=>data?.chart.slice(-(period==="7D"?7:period==="30D"?30:period==="90D"?90:365))??[],[data,period]);if(!data)return <section className="expanded-loading"><span className={error?"fallback-dot":"live-dot"}/><div><strong>{error||"正在同步 UNI 市场、协议与销毁数据"}</strong><small>价格、供应、协议成交、费用与真实销毁同时读取</small></div></section>;const p=data.protocol,s=data.supply,start=chart[0]?.[1]??data.price,change=start?(data.price/start-1)*100:0,maxChain=p.topChains[0]?.tvl??1;return <div className="uni-dashboard">
  <section className="uni-hero"><div><span className="section-kicker">UNISWAP FUNDAMENTALS</span><h1>UNI<em>协议使用如何转化为永久销毁</em></h1><p>交易量、手续费、协议费与链上 0xdead 余额使用独立口径核验。</p></div><aside><span className={data.failedSources.length?"fallback-dot":"live-dot"}/><strong>{data.failedSources.length?"部分数据源异常":"全部核心数据已同步"}</strong><small>{data.failedSources.join(" · ")||new Date(data.updatedAt).toLocaleTimeString("zh-CN")}</small></aside></section>
  <section className="metrics-grid uni-metrics"><article><span>UNI 当前价格</span><strong>${money(data.price,4)}</strong><small className={data.change24h>=0?"positive":"negative"}>{data.change24h>=0?"+":""}{data.change24h.toFixed(2)}% · 24H</small></article><article><span>流通市值</span><strong>${compact(data.marketCap)}</strong><small>FDV ${compact(data.fdv)}</small></article><article><span>协议 30D 成交</span><strong>${compact(p.volume30d)}</strong><small>7D ${compact(p.volume7d)}</small></article><article><span>协议 30D 手续费</span><strong>${compact(p.fees30d)}</strong><small>7D ${compact(p.fees7d)}</small></article><article><span>30D / 90D 销毁</span><strong>{s.burn30d==null?"—":`${compact(s.burn30d)} / ${compact(s.burn90d??0)}`}</strong><small>UNI · 0xdead余额变化</small></article><article><span>累计永久移除</span><strong>{s.burned==null?"—":`${compact(s.burned)} UNI`}</strong><small>{data.valueFlow.status}</small></article></section>
  <section className="dashboard-grid uni-top-grid"><article className="panel"><div className="panel-head"><div><span className="section-kicker">PRICE ACTION</span><h2>{period} 价格趋势</h2></div><div className="period-switch">{(["7D","30D","90D","1Y"] as Period[]).map(x=><button type="button" className={period===x?"active":""} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div></div><div className="price-summary"><strong>${money(data.price,4)}</strong><span className={change>=0?"positive":"negative"}>{change>=0?"↑":"↓"} {Math.abs(change).toFixed(2)}%</span></div><Chart data={chart}/><div className="chart-foot"><span>{chart[0]?new Date(chart[0][0]).toLocaleDateString("zh-CN"):"—"}</span><span>{data.chartSource}</span><span>现在</span></div></article><article className="panel uni-flywheel"><div className="panel-head"><div><span className="section-kicker">VALUE CAPTURE</span><h2>协议费销毁飞轮</h2></div></div><div className="uni-flow"><div><b>01</b><span><strong>协议交易</strong><small>30D ${compact(p.volume30d)}</small></span></div><i>→</i><div><b>02</b><span><strong>产生手续费</strong><small>30D ${compact(p.fees30d)}</small></span></div><i>→</i><div><b>03</b><span><strong>协议费购买 UNI</strong><small>{data.valueFlow.feeCoverage}</small></span></div><i>→</i><div><b>04</b><span><strong>永久销毁</strong><small>30D {s.burn30d==null?"—":compact(s.burn30d)} UNI</small></span></div></div><p className="micro-note">{data.valueFlow.method}；不会把普通转账或总供应差额误算为销毁。</p></article></section>
  <section className="dashboard-grid uni-lower-grid"><article className="panel"><div className="panel-head"><div><span className="section-kicker">PROTOCOL USE</span><h2>协议业务强度</h2></div></div><div className="uni-stat-list"><div><span>TVL</span><strong>{p.tvl==null?"—":`$${compact(p.tvl)}`}</strong></div><div><span>24H / 7D 成交</span><strong>${compact(p.volume24h)} / ${compact(p.volume7d)}</strong></div><div><span>24H / 7D 手续费</span><strong>${compact(p.fees24h)} / ${compact(p.fees7d)}</strong></div><div><span>7D 成交变化</span><strong className={p.changeVolume7d>=0?"positive":"negative"}>{p.changeVolume7d>=0?"+":""}{p.changeVolume7d.toFixed(1)}%</strong></div></div></article><article className="panel"><div className="panel-head"><div><span className="section-kicker">CHAIN MIX</span><h2>多链 TVL 分布</h2></div></div><div className="uni-chain-list">{p.topChains.map(chain=><div key={chain.name}><span>{chain.name}</span><i><b style={{width:`${Math.max(2,chain.tvl/maxChain*100)}%`}}/></i><strong>${compact(chain.tvl)}</strong></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="section-kicker">SUPPLY</span><h2>净供应状态</h2></div></div><div className="uni-stat-list"><div><span>整体供应基准</span><strong>{compact(s.maximum)} UNI</strong></div><div><span>当前总供应</span><strong>{compact(s.total)} UNI</strong></div><div><span>流通供应</span><strong>{compact(s.circulating)} UNI</strong></div><div><span>销毁后有效供应</span><strong>{compact(s.effectiveSupply)} UNI</strong></div></div><p className="micro-note">数据源：{s.source}{s.block?` · 区块 ${s.block}`:""}</p></article></section>
  <footer className="expanded-footer"><strong>UNI · Token Lens</strong><span>60 秒自动刷新</span></footer>
  </div>}
