import { NextResponse } from "next/server";

const UNI="0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984";
const DEAD="0x000000000000000000000000000000000000dEaD";
const RPCS=["https://ethereum-rpc.publicnode.com","https://eth.drpc.org","https://eth.llamarpc.com"];
const CG="https://api.coingecko.com/api/v3";

async function json(url:string,options:RequestInit={},timeout=9_000){const response=await fetch(url,{cache:"no-store",headers:{accept:"application/json",...(options.headers||{})},signal:AbortSignal.timeout(timeout),...options});if(!response.ok)throw new Error(`${response.status} ${url}`);return response.json()}
const median=(values:number[])=>{const rows=values.filter(Number.isFinite).sort((a,b)=>a-b);return rows.length?rows[Math.floor(rows.length/2)]:0};
async function rpc(method:string,params:unknown[]){let last:unknown;for(const url of RPCS){try{const result=await json(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params})},7_000);if(result.error||result.result==null)throw new Error(result.error?.message||"empty rpc");return result.result}catch(error){last=error}}throw last instanceof Error?last:new Error("rpc unavailable")}
const blockCall=async(data:string,block="latest")=>Number(BigInt(await rpc("eth_call",[{to:UNI,data},block])))/1e18;
const balanceData=(address:string)=>`0x70a08231${address.toLowerCase().replace(/^0x/,"").padStart(64,"0")}`;

async function supply(){const latest=Number.parseInt(await rpc("eth_blockNumber",[]),16),perDay=7_200;const [total,burned,burned30,burned90]=await Promise.all([blockCall("0x18160ddd"),blockCall(balanceData(DEAD)),blockCall(balanceData(DEAD),`0x${Math.max(1,latest-30*perDay).toString(16)}`),blockCall(balanceData(DEAD),`0x${Math.max(1,latest-90*perDay).toString(16)}`)]);return {total,burned,burn30d:Math.max(0,burned-burned30),burn90d:Math.max(0,burned-burned90),effectiveSupply:Math.max(0,total-burned),block:latest}}
async function exchange(){const settled=await Promise.allSettled([json("https://api.binance.com/api/v3/ticker/24hr?symbol=UNIUSDT"),json("https://www.okx.com/api/v5/market/ticker?instId=UNI-USDT"),json("https://api.bybit.com/v5/market/tickers?category=spot&symbol=UNIUSDT")]);const quotes:Array<{name:string;price:number;change:number;volume:number;high:number;low:number}>=[];if(settled[0].status==="fulfilled"){const x=settled[0].value;quotes.push({name:"Binance",price:Number(x.lastPrice),change:Number(x.priceChangePercent),volume:Number(x.quoteVolume),high:Number(x.highPrice),low:Number(x.lowPrice)})}if(settled[1].status==="fulfilled"){const x=settled[1].value.data?.[0],price=Number(x?.last),open=Number(x?.open24h);if(price>0)quotes.push({name:"OKX",price,change:open?(price/open-1)*100:0,volume:Number(x.volCcy24h),high:Number(x.high24h),low:Number(x.low24h)})}if(settled[2].status==="fulfilled"){const x=settled[2].value.result?.list?.[0],price=Number(x?.lastPrice);if(price>0)quotes.push({name:"Bybit",price,change:Number(x.price24hPcnt)*100,volume:Number(x.turnover24h),high:Number(x.highPrice24h),low:Number(x.lowPrice24h)})}return quotes}
async function chart(){const settled=await Promise.allSettled([json("https://api.binance.com/api/v3/klines?symbol=UNIUSDT&interval=1d&limit=365"),json("https://www.okx.com/api/v5/market/history-candles?instId=UNI-USDT&bar=1Dutc&limit=300")]);if(settled[0].status==="fulfilled")return {rows:settled[0].value.map((x:unknown[])=>[Number(x[0]),Number(x[4])] as [number,number]),source:"Binance"};if(settled[1].status==="fulfilled")return {rows:(settled[1].value.data??[]).map((x:string[])=>[Number(x[0]),Number(x[4])] as [number,number]).sort((a:[number,number],b:[number,number])=>a[0]-b[0]),source:"OKX"};return {rows:[] as Array<[number,number]>,source:"unavailable"}}
const metric=(x:any,key:string)=>Number(x?.[key])||0;

export async function GET(){
  const headers:Record<string,string>={accept:"application/json"};if(process.env.COINGECKO_API_KEY)headers["x-cg-demo-api-key"]=process.env.COINGECKO_API_KEY;
  const results=await Promise.allSettled([exchange(),chart(),json(`${CG}/coins/markets?vs_currency=usd&ids=uniswap&price_change_percentage=24h`,{headers}),supply(),json("https://api.llama.fi/protocol/uniswap"),json("https://api.llama.fi/summary/dexs/uniswap?dataType=dailyVolume"),json("https://api.llama.fi/summary/fees/uniswap?dataType=dailyFees")]);
  const [exchangeResult,chartResult,cgResult,supplyResult,protocolResult,volumeResult,feesResult]=results,quotes=exchangeResult.status==="fulfilled"?exchangeResult.value:[],cg=cgResult.status==="fulfilled"?cgResult.value?.[0]:null,price=median(quotes.map(x=>x.price))||Number(cg?.current_price)||0;
  if(!price)return NextResponse.json({error:"UNI 行情暂时不可用",updatedAt:new Date().toISOString()},{status:503,headers:{"Cache-Control":"no-store"}});
  const chainRaw=protocolResult.status==="fulfilled"?protocolResult.value.currentChainTvls??{}:{},topChains=Object.entries(chainRaw).filter(([name,value])=>!name.includes("-")&&Number(value)>0).map(([name,value])=>({name,tvl:Number(value)})).sort((a,b)=>b.tvl-a.tvl).slice(0,8),protocolTvl=protocolResult.status==="fulfilled"?Number(protocolResult.value.tvl)||topChains.reduce((sum,x)=>sum+x.tvl,0):null,volume=volumeResult.status==="fulfilled"?volumeResult.value:null,fees=feesResult.status==="fulfilled"?feesResult.value:null,onchain=supplyResult.status==="fulfilled"?supplyResult.value:null,circulating=Number(cg?.circulating_supply)||620_930_423,total=onchain?.total||Number(cg?.total_supply)||1_000_000_000,maximum=1_000_000_000;
  const failedSources=[!quotes.length&&"三所行情",chartResult.status!=="fulfilled"&&"价格历史",!onchain&&"UNI 销毁地址",protocolTvl==null&&"协议 TVL",!volume&&"协议成交",!fees&&"协议费用"].filter(Boolean);
  return NextResponse.json({
    price,change24h:quotes.length?median(quotes.map(x=>x.change)):Number(cg?.price_change_percentage_24h)||0,marketCap:circulating*price,fdv:maximum*price,volume24h:quotes.reduce((sum,x)=>sum+x.volume,0)||Number(cg?.total_volume)||0,high24h:quotes.length?Math.max(...quotes.map(x=>x.high)):null,low24h:quotes.length?Math.min(...quotes.map(x=>x.low)):null,venues:quotes,
    chart:chartResult.status==="fulfilled"?chartResult.value.rows:[],chartSource:chartResult.status==="fulfilled"?chartResult.value.source:"unavailable",
    supply:{circulating,total,maximum,effectiveSupply:onchain?.effectiveSupply??total,burned:onchain?.burned??null,burn30d:onchain?.burn30d??null,burn90d:onchain?.burn90d??null,block:onchain?.block??null,source:onchain?"Ethereum UNI balanceOf(0xdead)":"市场供应备用"},
    protocol:{tvl:protocolTvl,volume24h:metric(volume,"total24h"),volume7d:metric(volume,"total7d"),volume30d:metric(volume,"total30d"),volumeAllTime:metric(volume,"totalAllTime"),fees24h:metric(fees,"total24h"),fees7d:metric(fees,"total7d"),fees30d:metric(fees,"total30d"),feesAllTime:metric(fees,"totalAllTime"),changeVolume7d:metric(volume,"change_7d"),changeFees7d:metric(fees,"change_7d"),topChains,source:"DefiLlama Uniswap protocol summaries"},
    valueFlow:{status:"协议费用与程序化 UNI 销毁已运行",feeCoverage:"v2/v3 已扩展至多链；v4 按治理进度推进",burnDestination:DEAD,method:"以 0xdead 的 UNI 余额变化统计实际永久移除"},failedSources,updatedAt:new Date().toISOString()
  },{headers:{"Cache-Control":"public, max-age=15, s-maxage=30, stale-while-revalidate=90"}})
}
